-- Safe aggregate-only SQL checks. Do not SELECT raw values from private columns.
PRAGMA query_only=ON;
PRAGMA quick_check;
PRAGMA user_version;

SELECT version, name, applied_at FROM schema_migrations ORDER BY version;

-- Table inventory counts should be generated by code that iterates sqlite_master and runs COUNT(*).
-- Relevant point checks:
SELECT COUNT(*) AS email_raw_messages FROM email_message_raw_content;
SELECT COUNT(*) AS email_raw_threads FROM email_thread_raw_context;
SELECT COUNT(*) AS calendar_raw_events FROM calendar_event_raw_content;
SELECT COUNT(*) AS email_structured_messages FROM email_raw_message_structured;
SELECT COUNT(*) AS email_structured_threads FROM email_raw_thread_structured;
SELECT COUNT(*) AS calendar_structured_events FROM calendar_raw_event_structured;
SELECT COUNT(*) AS projection_runs FROM email_calendar_projection_runs;
SELECT COUNT(*) AS projection_coverage_rows FROM email_calendar_projection_coverage;
SELECT COUNT(*) AS raw_access_events FROM raw_content_access_events;
SELECT COUNT(*) AS procore_raw_payloads FROM procore_endpoint_raw_payloads;
SELECT COUNT(*) AS procore_action_signals FROM procore_action_signals;
SELECT COUNT(*) AS daily_candidates FROM daily_brief_action_candidates;
SELECT COUNT(*) AS candidate_source_refs FROM candidate_source_refs;
SELECT COUNT(*) AS daily_source_refs FROM daily_brief_source_refs;
SELECT COUNT(*) AS project_identities FROM construction_project_identity;
SELECT COUNT(*) AS project_keywords FROM construction_project_keyword_registry;
SELECT COUNT(*) AS project_source_matches FROM construction_project_source_matches;
SELECT COUNT(*) AS follow_up_watch_items FROM follow_up_watch_items;
SELECT COUNT(*) AS email_followup_enrichments FROM email_followup_enrichments;
SELECT COUNT(*) AS task_candidates FROM task_candidates;
SELECT COUNT(*) AS commitment_candidates FROM commitment_candidates;

SELECT source_quality, COUNT(*) FROM email_message_raw_content GROUP BY source_quality ORDER BY COUNT(*) DESC;
SELECT source_quality, COUNT(*) FROM calendar_event_raw_content GROUP BY source_quality ORDER BY COUNT(*) DESC;
SELECT source_quality, COUNT(*) FROM procore_endpoint_raw_payloads GROUP BY source_quality ORDER BY COUNT(*) DESC;

SELECT brief_date, section, COUNT(*)
FROM daily_brief_action_candidates
GROUP BY brief_date, section
ORDER BY brief_date DESC, section;

SELECT signal_status, COUNT(*) FROM procore_action_signals GROUP BY signal_status ORDER BY COUNT(*) DESC;
SELECT signal_type, COUNT(*) FROM procore_action_signals GROUP BY signal_type ORDER BY COUNT(*) DESC LIMIT 25;

-- Guard-column checks: build dynamically for all columns named like raw_body_emitted%, raw_payload_emitted%, external_writeback_performed.
