"""V113 — N8C-24 Connected Client Generated File Output Workspace.

A remote-safe, audited, bounded output workspace for non-canonical work products (docx/xlsx/pptx/pdf/
md/txt/csv/json/html/zip) generated by connected LLM clients and written under the governed ``outputs``
root — never the Obsidian vault and never canonical promotion. Writes are staged, then committed only
behind a server-minted approval + idempotency key; every commit produces a receipt and updates a
manifest. Archive is staged + explicit and never deletes. All tables ship EMPTY.
"""

from __future__ import annotations


def _csv(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{v}'" for v in values)


# Lifecycle of a staged/committed generated output.
OUTPUT_STATUS_VALUES: tuple[str, ...] = (
    "staged",
    "validation_failed",
    "ready_to_commit",
    "committed",
    "commit_failed",
    "archived",
    "superseded",
)

# Receipt kinds written under 99 Receipts.
OUTPUT_RECEIPT_TYPE_VALUES: tuple[str, ...] = (
    "stage",
    "commit",
    "archive",
    "validation_failure",
)

# How the client provided/asked us to render the payload.
CONTENT_MODE_VALUES: tuple[str, ...] = (
    "text",
    "csv_text",
    "json_text",
    "markdown_text",
    "html_text",
    "base64_binary",
    "docx_from_markdown_or_text",
    "xlsx_from_csv",
    "pptx_from_markdown_or_json",
    "pdf_from_html_or_markdown",
    "zip_base64",
    "zip_from_outputs",
)

# Allowed generated-output file types (mirrors DEFAULT_CLIENT_OUTPUT_WRITE_EXTENSIONS).
FILE_TYPE_VALUES: tuple[str, ...] = (
    "txt", "md", "csv", "json", "docx", "xlsx", "pptx", "pdf", "html", "zip",
)


V113_CLIENT_OUTPUT_STATEMENTS: list[str] = [
    f"""
    CREATE TABLE IF NOT EXISTS assistant_output_files (
      output_id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      filename TEXT NOT NULL,
      file_type TEXT NOT NULL CHECK(file_type IN ({_csv(FILE_TYPE_VALUES)})),
      content_mode TEXT NOT NULL CHECK(content_mode IN ({_csv(CONTENT_MODE_VALUES)})),
      status TEXT NOT NULL DEFAULT 'staged' CHECK(status IN ({_csv(OUTPUT_STATUS_VALUES)})),
      source_client TEXT,
      source_session_id TEXT,
      related_canonical_ids_json TEXT,
      related_proposal_ids_json TEXT,
      relative_path TEXT,
      root_key TEXT NOT NULL DEFAULT 'outputs',
      path_display TEXT,
      destination_state TEXT NOT NULL DEFAULT 'pending',
      bytes_written INTEGER,
      sha256 TEXT,
      content_hash TEXT,
      staged_content_hash TEXT,
      staged_content_b64 TEXT,
      validation_summary_json TEXT,
      zip_validation_json TEXT,
      operator_approval_required INTEGER NOT NULL DEFAULT 1 CHECK(operator_approval_required IN (0,1)),
      operator_approval_id TEXT,
      operator_approved_at TEXT,
      idempotency_key TEXT,
      receipt_id TEXT,
      manifest_id TEXT,
      created_by TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      committed_at TEXT,
      archived_at TEXT,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_assistant_output_files_status "
    "ON assistant_output_files(status, file_type, created_at)",
    "CREATE INDEX IF NOT EXISTS idx_assistant_output_files_session "
    "ON assistant_output_files(source_session_id)",
    """
    CREATE TABLE IF NOT EXISTS assistant_output_file_versions (
      output_version_id TEXT PRIMARY KEY,
      output_id TEXT NOT NULL,
      version INTEGER NOT NULL,
      filename TEXT NOT NULL,
      relative_path TEXT,
      bytes_written INTEGER,
      sha256 TEXT,
      change_summary TEXT,
      supersedes_version_id TEXT,
      created_by TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_assistant_output_file_versions_output "
    "ON assistant_output_file_versions(output_id, version)",
    f"""
    CREATE TABLE IF NOT EXISTS assistant_output_file_receipts (
      receipt_id TEXT PRIMARY KEY,
      output_id TEXT NOT NULL,
      receipt_type TEXT NOT NULL CHECK(receipt_type IN ({_csv(OUTPUT_RECEIPT_TYPE_VALUES)})),
      status TEXT NOT NULL,
      relative_receipt_path TEXT,
      bytes_written INTEGER,
      sha256 TEXT,
      validation_summary_json TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_assistant_output_file_receipts_output "
    "ON assistant_output_file_receipts(output_id, receipt_type)",
    f"""
    CREATE TABLE IF NOT EXISTS assistant_output_file_manifest_entries (
      manifest_entry_id TEXT PRIMARY KEY,
      output_id TEXT NOT NULL,
      title TEXT,
      file_type TEXT CHECK(file_type IN ({_csv(FILE_TYPE_VALUES)})),
      status TEXT,
      relative_path TEXT,
      receipt_path TEXT,
      sha256 TEXT,
      source_client TEXT,
      source_session_id TEXT,
      related_canonical_ids_json TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_assistant_output_manifest_entries_output "
    "ON assistant_output_file_manifest_entries(output_id)",
]
