"""Phase 10J — summary-quality hardening (source-grounded, classification-aware five-section gate).

Proves the deterministic quality layer added to ``source_local_summary`` for the 10J source-card
summary path: document-family detection from title/header, classifier-conflict surfacing (NOT repair),
excerpt grounding, and ``validate_summary_quality`` gates against the three real failure families —
a value-analysis tracking log wrongly typed ``warranty``, a generic MasterWorks mold-remediation
specification wrongly typed ``submittal``, and a preconstruction clarification/questions memo wrongly
typed ``scope_of_work``. Each family is exercised with a bad (rejected) and a good (accepted) summary.

Synthetic excerpts only — no real Ollama, no vault, no DB.
"""

from __future__ import annotations

from hb_assistant.obsidian_mcp import source_local_summary as sls


def _lines(text: str) -> list[str]:
    return text.splitlines()


# --------------------------------------------------------------------------- family excerpts + titles
_VA_TITLE = "20241016 TWN VA Log"
_VA_EXCERPT = (
    "VALUE ANALYSIS TRACKING LOG\n"
    "Item 1 Alternate glazing system  Status Open     Value #REF!\n"
    "Item 2 Roofing membrane          Status Accepted Value 45000\n"
    "Item 3 HVAC controls             Status Rejected Value 12000\n"
)
_MOLD_TITLE = "Section 02 87 13 Mold Remediation"
_MOLD_EXCERPT = (
    "SECTION 02 87 13 MOLD REMEDIATION — MasterWorks generic specification.\n"
    "PART 1 GENERAL. The contractor shall clean, kill, and coat affected surfaces and correct the "
    "moisture source. Comply with IICRC S520. Submittals: product data, SDS, and VOC content. "
    "Provide manufacturer remediation products.\n"
)
_MEMO_TITLE = "1"
_MEMO_EXCERPT = (
    "PRECONSTRUCTION CLARIFICATION MEMO. Open questions for the team: What is the final foundation "
    "elevation? Who provides temporary power? When will the geotechnical report be issued?\n"
)


# --------------------------------------------------------------------------- _title_signal
def test_title_signal_value_analysis_log():
    assert sls._title_signal(_VA_TITLE, _VA_EXCERPT) == "value_analysis_log"


def test_title_signal_specification_generic_from_spec_section():
    assert sls._title_signal(_MOLD_TITLE, _MOLD_EXCERPT) == "specification_generic"
    # section number in the excerpt header alone is enough, even with a bland title
    assert sls._title_signal("attachment", _MOLD_EXCERPT) == "specification_generic"


def test_title_signal_memo_questions():
    assert sls._title_signal(_MEMO_TITLE, _MEMO_EXCERPT) == "memo_questions"


def test_title_signal_none_for_plain_document():
    assert sls._title_signal("Meeting Notes", "The team met to review the schedule.") is None


# --------------------------------------------------------------------------- classification conflict
def test_detect_conflict_va_log_typed_warranty():
    assert sls.detect_classification_conflict("warranty", _VA_TITLE, _VA_EXCERPT) == "value_analysis_log"


def test_detect_conflict_generic_spec_typed_submittal():
    assert sls.detect_classification_conflict("submittal", _MOLD_TITLE, _MOLD_EXCERPT) \
        == "specification_generic"


def test_detect_conflict_memo_typed_scope_of_work():
    assert sls.detect_classification_conflict("scope_of_work", _MEMO_TITLE, _MEMO_EXCERPT) \
        == "memo_questions"


def test_no_conflict_when_type_matches_family():
    # A value-analysis log typed as a log/tracker is consistent → no conflict surfaced.
    assert sls.detect_classification_conflict("value_analysis", _VA_TITLE, _VA_EXCERPT) is None


# --------------------------------------------------------------------------- VA log family
_VA_BAD = (
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source._\n\n"
    "### Summary\nThis warranty document lists building systems and their acceptance status.\n\n"
    "### Key Extracted Details\n- Glazing system status open.\n- Roofing membrane accepted.\n"
    "- HVAC controls rejected.\n\n"
    "### PM Attention\n- Review the warranty coverage.\n\n"
    "### Follow-Up Questions\n- Which systems remain open?\n\n"
    "### Limits / Uncertainty\n- Advisory only.\n"
)
_VA_GOOD = (
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source._\n\n"
    "### Summary\nA value-analysis tracking log recording cost-saving alternates and their disposition "
    "status.\n\n"
    "### Key Extracted Details\n- Line items cover glazing, roofing membrane, and HVAC controls.\n"
    "- Statuses range from open to accepted to rejected.\n"
    "- One alternate value cell shows a #REF spreadsheet error needing correction.\n\n"
    "### PM Attention\n- Verify the #REF value and confirm each alternate's disposition.\n\n"
    "### Follow-Up Questions\n- What is the corrected value for the glazing alternate?\n\n"
    "### Limits / Uncertainty\n- Value-analysis log; some cells contain #REF data-quality errors.\n"
)


def test_va_log_summarized_as_warranty_rejected():
    ok, reason = sls.validate_summary_quality(
        _lines(_VA_BAD), {"text_excerpt": _VA_EXCERPT}, title=_VA_TITLE, document_type="warranty")
    assert not ok and reason == "classification_conflict"


def test_va_log_grounded_value_analysis_summary_ok():
    ok, reason = sls.validate_summary_quality(
        _lines(_VA_GOOD), {"text_excerpt": _VA_EXCERPT}, title=_VA_TITLE, document_type="warranty")
    assert ok and reason == "ok"


# --------------------------------------------------------------------------- generic spec family
_MOLD_BAD = (
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source._\n\n"
    "### Summary\nA project-specific submittal package for mold cleanup on this building.\n\n"
    "### Key Extracted Details\n- Contractor to clean, kill, and coat affected surfaces.\n"
    "- Correct the moisture source.\n- Comply with IICRC S520.\n\n"
    "### PM Attention\n- Track the submittal review.\n\n"
    "### Follow-Up Questions\n- When is the submittal due?\n\n"
    "### Limits / Uncertainty\n- Advisory only.\n"
)
_MOLD_GOOD = (
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source._\n\n"
    "### Summary\nA generic MasterWorks specification (Section 02 87 13) for mold remediation, not "
    "project-specific.\n\n"
    "### Key Extracted Details\n- Remediation approach: clean, kill, and coat affected surfaces.\n"
    "- Requires correcting the moisture source and compliance with IICRC S520.\n"
    "- Submittals include product data, SDS, and VOC content.\n\n"
    "### PM Attention\n- Confirm the contractor's submittals (SDS, VOC) meet the generic spec.\n\n"
    "### Follow-Up Questions\n- Which manufacturer products will be proposed?\n\n"
    "### Limits / Uncertainty\n- Generic template specification; project-specific selections not yet "
    "stated.\n"
)


def test_generic_spec_framed_as_project_submittal_rejected():
    ok, reason = sls.validate_summary_quality(
        _lines(_MOLD_BAD), {"text_excerpt": _MOLD_EXCERPT}, title=_MOLD_TITLE, document_type="submittal")
    assert not ok and reason == "generic_spec_unqualified"


def test_generic_spec_qualified_summary_ok():
    ok, reason = sls.validate_summary_quality(
        _lines(_MOLD_GOOD), {"text_excerpt": _MOLD_EXCERPT}, title=_MOLD_TITLE, document_type="submittal")
    assert ok and reason == "ok"


# --------------------------------------------------------------------------- memo / questions family
# The memo is short with no strong deterministic keyword beyond grounding: a boilerplate "scope of work"
# reframing that ignores the actual questions fails the excerpt-grounding gate.
_MEMO_BAD = (
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source._\n\n"
    "### Summary\nA formal scope of work defining contractual deliverables and responsibilities.\n\n"
    "### Key Extracted Details\n- Defines contractor obligations.\n- Lists general requirements.\n"
    "- Establishes performance standards.\n\n"
    "### PM Attention\n- Execute per the agreement.\n\n"
    "### Follow-Up Questions\n- None noted.\n\n"
    "### Limits / Uncertainty\n- Advisory only.\n"
)
_MEMO_GOOD = (
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source._\n\n"
    "### Summary\nA preconstruction clarification memo listing open questions for the project team.\n\n"
    "### Key Extracted Details\n- Open question: final foundation elevation.\n"
    "- Open question: who provides temporary power.\n"
    "- Open question: when the geotechnical report will be issued.\n\n"
    "### PM Attention\n- Route each open question to the responsible party for a written answer.\n\n"
    "### Follow-Up Questions\n- Have the foundation elevation and temporary power questions been "
    "resolved?\n\n"
    "### Limits / Uncertainty\n- Clarification memo, not a scope of work; answers pending.\n"
)


def test_memo_reframed_as_scope_is_ungrounded():
    ok, reason = sls.validate_summary_quality(
        _lines(_MEMO_BAD), {"text_excerpt": _MEMO_EXCERPT}, title=_MEMO_TITLE,
        document_type="scope_of_work")
    assert not ok and reason == "ungrounded"


def test_memo_clarification_summary_preserving_questions_ok():
    ok, reason = sls.validate_summary_quality(
        _lines(_MEMO_GOOD), {"text_excerpt": _MEMO_EXCERPT}, title=_MEMO_TITLE,
        document_type="scope_of_work")
    assert ok and reason == "ok"


# --------------------------------------------------------------------------- cross-cutting gates
def test_four_section_shape_rejected_as_format_invalid():
    # Old four-section advisory (no "Key Extracted Details") is invalid for source cards.
    four = (
        "_Advisory_\n\n### Summary\nx grounded glazing roofing membrane.\n\n"
        "### PM Attention\n- a\n\n### Follow-Up Questions\n- b\n\n### Limits / Uncertainty\n- c\n")
    ok, reason = sls.validate_summary_quality(
        _lines(four), {"text_excerpt": _VA_EXCERPT}, title="x", document_type="rfi")
    assert not ok and reason == "format_invalid"


def test_ungrounded_when_summary_ignores_excerpt():
    generic = (
        "_Advisory_\n\n### Summary\nA generic administrative document.\n\n"
        "### Key Extracted Details\n- General routine content only.\n\n"
        "### PM Attention\n- Nothing specific.\n\n### Follow-Up Questions\n- None.\n\n"
        "### Limits / Uncertainty\n- Advisory only.\n")
    ok, reason = sls.validate_summary_quality(
        _lines(generic), {"text_excerpt": _VA_EXCERPT}, title="x", document_type="rfi")
    assert not ok and reason == "ungrounded"


def test_missing_ref_data_quality_note_rejected():
    # Excerpt has #REF; a grounded VA summary that omits any #REF/data-quality note is rejected.
    no_ref = (
        "_Advisory_\n\n### Summary\nA value-analysis tracking log of alternates and their status.\n\n"
        "### Key Extracted Details\n- Line items: glazing, roofing membrane, HVAC controls.\n"
        "- Statuses: open, accepted, rejected.\n\n"
        "### PM Attention\n- Confirm each alternate value and status.\n\n"
        "### Follow-Up Questions\n- Which alternates remain open?\n\n"
        "### Limits / Uncertainty\n- Value-analysis log; values need verification.\n")
    ok, reason = sls.validate_summary_quality(
        _lines(no_ref), {"text_excerpt": _VA_EXCERPT}, title=_VA_TITLE, document_type="warranty")
    assert not ok and reason == "missing_data_quality_note"
