"""Phase 10B — bounded local qwen2.5:14b advisory-summary appender. Synthetic temp only; no real Ollama.

Proves marker-only replacement, byte-preservation of deterministic sections, boundedness/sanitation,
no source-file read, no index/scan/queue activity, no DB mutation, fail-safe on model error, and the
strictly-additive client `generate_text`.
"""

from __future__ import annotations

import importlib.util
import json
import sqlite3
from pathlib import Path

import pytest

from hb_assistant.construction.classification.client import OllamaChatClient, OllamaUnavailable
from hb_assistant.obsidian_mcp.config import ObsidianMcpConfig
from hb_assistant.obsidian_mcp.source_index_repository import SourceIndexRepository
from hb_assistant.obsidian_mcp.source_indexer import index_source_file
from hb_assistant.obsidian_mcp.source_notes import generate_source_card
from hb_assistant.store.migrator import SQLiteMigrator

_SCRIPT = (Path(__file__).resolve().parents[1] / "scripts"
           / "obsidian_source_card_append_local_summary.py")
_spec = importlib.util.spec_from_file_location("append_local_summary", _SCRIPT)
assert _spec and _spec.loader
mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(mod)

_GOOD_MD = (
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source._\n\n"
    "### Summary\nConcise advisory for a test card.\n\n"
    "### PM Attention\n- Confirm the document type.\n\n"
    "### Follow-Up Questions\n- Is this current?\n\n"
    "### Limits / Uncertainty\n- Metadata-only; low confidence.\n"
)
_SEED = [
    ("25-244/RFI 032 - Door Hardware.md", "Request for Information RFI #032 regarding door hardware."),
    ("25-244/Executed Change Order 004.md", "Executed change order. Change Order Amount: $12,500.00."),
    ("25-244/Project Notes.md", "# Notes\n\nGeneral project notes for the team."),
]


class _FakeClient:
    base_url = "http://localhost:11434"

    def __init__(self, *, text: str = _GOOD_MD, exc: Exception | None = None):
        self._text, self._exc = text, exc
        self.calls = 0

    def generate_text(self, *, system: str, prompt: str) -> str:
        self.calls += 1
        if self._exc is not None:
            raise self._exc
        return self._text


@pytest.fixture(autouse=True)
def _no_backend(monkeypatch):
    monkeypatch.setattr(mod, "_backend_listening", lambda *a, **k: False)
    # default: model available
    monkeypatch.setattr(mod, "list_ollama_models", lambda **k: ["qwen2.5:14b", "llama3.1"])


def _env(tmp_path: Path, monkeypatch):
    vault = tmp_path / "vault"
    vault.mkdir(exist_ok=True)
    cyml = tmp_path / "c.yml"
    cyml.write_text(
        f"paths:\n  application_support_root: {str(tmp_path / 'as')!r}\n"
        f"  obsidian_vault: {vault.as_posix()!r}\n")
    monkeypatch.setenv("HB_PA_CONFIG", str(cyml))
    db = str(tmp_path / "db.sqlite")
    SQLiteMigrator(db_path=db).apply()
    root = tmp_path / "syn-source"
    (root / "25-244").mkdir(parents=True)
    cfg = {"enabled": True, "vault_root": str(vault), "writes_enabled": True,
           "vault_markdown_write_enabled": True, "source_card_generation_enabled": True,
           "external_sources": [{"source_root_key": "syn-work", "path": str(root), "enabled": True}]}
    cfgp = tmp_path / "cfg.json"
    cfgp.write_text(json.dumps(cfg))
    config = ObsidianMcpConfig.model_validate(cfg)
    repo = SourceIndexRepository(db)
    for rel, body in _SEED:
        f = root / rel
        f.write_text(body, encoding="utf-8")
        sid = index_source_file(f, config.external_sources[0], repo, config)
        generate_source_card(repo, config, source_id=sid)
    return {"db": db, "cfgp": str(cfgp), "vault": vault, "root": root, "repo": repo, "tmp": tmp_path}


def _args(env, *, apply=False, confirm=True, **over):
    a = ["--db-path", env["db"], "--config-path", env["cfgp"], "--vault-path", str(env["vault"]),
         "--domain", "work", "--model", "qwen2.5:14b", "--max-cards", "25",
         "--expected-work-generated", "3", "--evidence-dir", str(env["tmp"] / "ev"),
         "--backup-dir", str(env["tmp"] / "bk"), "--json-output"]
    if apply:
        a.append("--apply")
        if confirm:
            a += ["--confirm-db-path", env["db"], "--confirm-vault-path", str(env["vault"]),
                  "--confirm-model", "qwen2.5:14b"]
    for k, v in over.items():
        flag = "--" + k.replace("_", "-")
        a.append(flag) if v is True else a.extend([flag, str(v)])
    return a


def _run(argv, capsys, **kw):
    rc = mod.main(argv, **kw)
    out = capsys.readouterr().out
    return rc, (json.loads(out) if rc == 0 and out.strip() else None)


def _work_cards(env):
    return sorted((env["vault"] / "Source Notes" / "Work").glob("*.md"))


def _block_bounds(text):
    lines = text.splitlines()
    s = next(i for i, ln in enumerate(lines) if ln.startswith(mod.LOCAL_SUMMARY_BEGIN_PREFIX))
    e = next(i for i, ln in enumerate(lines) if ln.strip() == mod.LOCAL_SUMMARY_END)
    return lines, s, e


# ------------------------------------------------------------------------------- dry-run / refusals

def test_dry_run_selects_eligible_without_calling_ollama(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)

    def _boom_factory(model, timeout):
        raise AssertionError("Ollama must not be constructed in dry-run")

    rc, out = _run(_args(env), capsys, client_factory=_boom_factory)
    assert rc == 0
    assert out["mode"] == "dry-run" and out["selected"] == 3 and out["eligible"] == 3
    assert out["ollama_called"] is False and out["summarized"] == 0
    assert not list((tmp_path / "bk").glob("**/*.md"))  # no backups in dry-run


def test_apply_refuses_without_confirms(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    rc, _ = _run(_args(env, apply=True, confirm=False), capsys,
                 client_factory=lambda m, t: _FakeClient())
    assert rc == 3


def test_apply_refuses_when_backend_listening(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    monkeypatch.setattr(mod, "_backend_listening", lambda *a, **k: True)
    rc, _ = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 3


def test_apply_refuses_when_queue_not_empty(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    c = sqlite3.connect(env["db"])
    c.execute("INSERT INTO source_intelligence_events (event_type, rel_path, source_root_key, status)"
              " VALUES ('modified','x','syn-work','queued')")
    c.commit()
    c.close()
    rc, _ = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 3


def test_apply_refuses_on_unexpected_generated_count(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    rc, _ = _run(_args(env, apply=True, expected_work_generated=99), capsys,
                 client_factory=lambda m, t: _FakeClient())
    assert rc == 3


def test_apply_refuses_when_ollama_unavailable(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    monkeypatch.setattr(mod, "list_ollama_models",
                        lambda **k: (_ for _ in ()).throw(OllamaUnavailable("ollama_request_failed")))
    rc, _ = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 3
    assert not list((tmp_path / "bk").glob("**/*.md"))  # nothing touched


def test_apply_refuses_when_model_not_installed(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    monkeypatch.setattr(mod, "list_ollama_models", lambda **k: ["llama3.1"])
    rc, _ = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 3


def test_dry_run_flags_missing_marker_as_ineligible(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    card = _work_cards(env)[0]
    txt = card.read_text().replace(mod.LOCAL_SUMMARY_END, "")  # remove end marker
    card.write_text(txt, encoding="utf-8")
    rc, out = _run(_args(env), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 0 and out["eligible"] == 2 and out["ineligible"] == 1


def test_dry_run_flags_duplicate_marker_as_ineligible(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    card = _work_cards(env)[0]
    card.write_text(card.read_text() + "\n<!-- hb-local-summary:start model=\"x\" status=\"pending\" -->\n"
                    "<!-- hb-local-summary:end -->\n", encoding="utf-8")
    rc, out = _run(_args(env), capsys, client_factory=lambda m, t: _FakeClient())
    assert out["ineligible"] == 1


def test_dry_run_flags_wrong_card_version(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    card = _work_cards(env)[0]
    card.write_text(card.read_text().replace('card_version: "phase10a-v1"',
                                             'card_version: "phase8-v1"'), encoding="utf-8")
    rc, out = _run(_args(env), capsys, client_factory=lambda m, t: _FakeClient())
    assert out["ineligible"] == 1


def test_apply_refuses_already_generated_without_flag(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    # First apply generates all 3.
    _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    # Second apply: all already generated → eligible 0 (skipped), summarized 0.
    rc, out = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 0 and out["eligible"] == 0 and out["summarized"] == 0
    # With --allow-resummarize they become eligible again.
    rc2, out2 = _run(_args(env, apply=True, allow_resummarize=True), capsys,
                     client_factory=lambda m, t: _FakeClient())
    assert rc2 == 0 and out2["eligible"] == 3


# ------------------------------------------------------------------------------- apply behavior

def test_apply_summarizes_and_flips_marker(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    rc, out = _run(_args(env, apply=True), capsys,
                   client_factory=lambda m, t: _FakeClient(), now_iso_fn=lambda: "2026-06-30T23:00:00Z")
    assert rc == 0
    assert out["summarized"] == 3 and out["failed"] == 0 and out["created"] == 0
    assert out["deleted"] == 0 and out["queue_delta"] == 0
    assert out["db_mutation_detected"] is False and out["pilot_full_success"] is True
    for card in _work_cards(env):
        text = card.read_text()
        assert 'status="generated"' in text and 'generated_at="2026-06-30T23:00:00Z"' in text
        assert text.count("hb-local-summary:start") == 1 and text.count("hb-local-summary:end") == 1
        assert "Concise advisory for a test card." in text
    assert len(list((tmp_path / "bk" / "Source Notes" / "Work").glob("*.md"))) == 3


def test_apply_replaces_only_block_byte_preserving_rest(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    before = {c.name: c.read_text() for c in _work_cards(env)}
    _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    for card in _work_cards(env):
        new = card.read_text()
        ob = before[card.name]
        ol, os_, oe = _block_bounds(ob)
        nl, ns, ne = _block_bounds(new)
        # everything before the start marker and after the end marker is byte-identical
        assert ol[:os_] == nl[:ns]
        assert ol[oe + 1:] == nl[ne + 1:]
        # the only changed start line is the marker's status/generated_at
        assert nl[ns].startswith('<!-- hb-local-summary:start model="qwen2.5:14b" status="generated"')


def test_apply_failed_model_leaves_card_unchanged(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    before = {c.name: c.read_text() for c in _work_cards(env)}
    rc, out = _run(_args(env, apply=True), capsys,
                   client_factory=lambda m, t: _FakeClient(exc=OllamaUnavailable("ollama_timeout")))
    assert rc == 0 and out["summarized"] == 0 and out["failed"] == 3
    assert out["pilot_full_success"] is False
    after = {c.name: c.read_text() for c in _work_cards(env)}
    assert before == after  # cards untouched on model failure


def test_apply_empty_model_response_leaves_card_unchanged(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    before = {c.name: c.read_text() for c in _work_cards(env)}
    rc, out = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient(text="   "))
    assert rc == 0 and out["failed"] == 3 and out["summarized"] == 0
    assert {c.name: c.read_text() for c in _work_cards(env)} == before


def test_apply_makes_no_db_mutation(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)

    def snap():
        c = sqlite3.connect(env["db"])
        try:
            return (c.execute("SELECT COUNT(*) FROM source_intelligence_generated_notes").fetchone()[0],
                    c.execute("SELECT COUNT(*) FROM source_intelligence_summaries").fetchone()[0],
                    c.execute("SELECT COUNT(*) FROM source_intelligence_events").fetchone()[0])
        finally:
            c.close()

    b = snap()
    rc, out = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 0 and out["db_mutation_detected"] is False
    assert snap() == b


def test_apply_no_create_or_delete(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    names = {c.name for c in _work_cards(env)}
    rc, out = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    assert out["created"] == 0 and out["deleted"] == 0
    assert {c.name for c in _work_cards(env)} == names


def test_apply_does_not_read_external_source_files(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    import builtins
    real_open = builtins.open

    def guard(path, *a, **k):
        if "/syn-source/" in str(path):
            raise AssertionError(f"external source file read: {path}")
        return real_open(path, *a, **k)

    monkeypatch.setattr(builtins, "open", guard)
    rc, out = _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 0 and out["summarized"] == 3


def test_max_cards_cap_enforced(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    rc, _ = _run(_args(env, apply=True, max_cards=2), capsys, client_factory=lambda m, t: _FakeClient())
    assert rc == 3  # 3 eligible > cap 2


# ------------------------------------------------------------------------------- module/prompt hygiene

def test_appender_has_no_index_scan_or_queue_calls():
    src = _SCRIPT.read_text()
    for forbidden in ("index_source_file", "scan_source_root", "drain_queue", "enqueue_event",
                      "claim_queued", "upsert_summary", "delete_summary"):
        assert forbidden not in src, forbidden


def test_prompt_carries_advisory_boundary_and_omits_paths(tmp_path, monkeypatch):
    from hb_assistant.obsidian_mcp import source_local_summary as s
    assert "advisory" in s.LOCAL_SUMMARY_SYSTEM_PROMPT.lower()
    assert "do not invent" in s.LOCAL_SUMMARY_SYSTEM_PROMPT.lower()
    assert "not detected" in s.LOCAL_SUMMARY_SYSTEM_PROMPT.lower()
    card = ("---\nsource_path: \"/Volumes/secret/Obsidian Vault/x.pdf\"\ncard_version: \"phase10a-v1\"\n---\n"
            "# Source Card: x\n\n## Source Summary\n- a\n")
    prompt = s.build_summary_prompt(card, {"text_excerpt": "bounded excerpt"}, max_input_chars=6000)
    assert "/Volumes/secret" not in prompt  # frontmatter (with source_path) stripped
    assert "bounded excerpt" in prompt


def test_template_card_gets_cautious_prompt(tmp_path, monkeypatch):
    from hb_assistant.obsidian_mcp import source_local_summary as s
    sysp = s.LOCAL_SUMMARY_SYSTEM_PROMPT.lower()
    assert "template" in sysp and "non-authoritative" in sysp and "metadata-only" in sysp


def test_sanitizer_strips_unsafe_constructs():
    from hb_assistant.obsidian_mcp import source_local_summary as s
    dirty = ("```markdown\n### Summary\nok\n```\n"
             "<!-- hb-local-summary:start -->\n---\n"
             "See /Volumes/external/secret.md\n"
             "[link](../local/file.md)\n"
             "| a | b |\n| - | - |\n"
             "### PM Attention\n- fine\n")
    out = s.sanitize_advisory_markdown(dirty)
    joined = "\n".join(out)
    assert "```" not in joined and "hb-local-summary" not in joined and "<!--" not in joined
    assert "/Volumes/" not in joined and "](" not in joined and "|" not in joined
    assert "\n---\n" not in ("\n" + joined + "\n")
    assert "ok" in joined and "fine" in joined


def test_sanitizer_returns_empty_when_nothing_safe():
    from hb_assistant.obsidian_mcp import source_local_summary as s
    assert s.sanitize_advisory_markdown("```\n```\n<!-- x -->\n/Volumes/a") == []


# ------------------------------------------------------------------------------- client (additive)

def test_generate_text_omits_json_format(monkeypatch):
    captured = {}

    class _Resp:
        status_code = 200

        def json(self):
            return {"response": "hello markdown"}

    import hb_assistant.construction.classification.client as clientmod
    monkeypatch.setattr(clientmod.requests, "post",
                        lambda url, json, timeout: (captured.update(json) or _Resp()))
    c = OllamaChatClient(model="qwen2.5:14b")
    assert c.generate_text(system="s", prompt="p") == "hello markdown"
    assert "format" not in captured  # raw-text path must NOT force JSON
    assert captured["stream"] is False and captured["model"] == "qwen2.5:14b"


def test_generate_json_still_forces_json(monkeypatch):
    captured = {}

    class _Resp:
        status_code = 200

        def json(self):
            return {"response": "{}"}

    import hb_assistant.construction.classification.client as clientmod
    monkeypatch.setattr(clientmod.requests, "post",
                        lambda url, json, timeout: (captured.update(json) or _Resp()))
    c = OllamaChatClient(model="qwen2.5:14b")
    c.generate_json(system="s", prompt="p")
    assert captured["format"] == "json"  # unchanged behavior


def test_safe_summary_has_no_paths_or_bodies(tmp_path, monkeypatch, capsys):
    env = _env(tmp_path, monkeypatch)
    _run(_args(env, apply=True), capsys, client_factory=lambda m, t: _FakeClient())
    safe = (tmp_path / "ev" / "append-local-summary-work-apply-summary-safe.json").read_text()
    for needle in ("25-244", "RFI 032", "Door Hardware", "Concise advisory", str(env["vault"]),
                   str(env["root"]), "__"):
        assert needle not in safe, needle
