"""Phase 10F correction — validate_advisory quality gate (pure; no model, no I/O).

Enforces the canonical Phase 10B advisory shape and rejects deterministic-metadata contradictions and
duplicate/noncanonical shapes. Synthetic strings only.
"""

from __future__ import annotations

from hb_assistant.obsidian_mcp import source_local_summary as sls

_PDF = {"file_ext": "pdf", "document_type": "submittal", "size_bytes": 101015}
_XLSX = {"file_ext": "xlsx", "document_type": "spreadsheet", "size_bytes": 101015}


def _canonical(summary="This is a bounded advisory about the document.") -> list[str]:
    return [
        "_Advisory — locally generated by qwen2.5:14b. Verify against the source._",
        "",
        "### Summary",
        summary,
        "",
        "### PM Attention",
        "- Confirm the purpose against the source.",
        "",
        "### Follow-Up Questions",
        "- What is the disposition?",
        "",
        "### Limits / Uncertainty",
        "- Advisory only; verify before relying on this.",
    ]


def test_canonical_summary_passes():
    ok, reason = sls.validate_advisory(_canonical(), _PDF)
    assert ok and reason == "ok"


def test_missing_heading_is_format_invalid():
    lines = [ln for ln in _canonical() if ln != "### Follow-Up Questions"]
    ok, reason = sls.validate_advisory(lines, _PDF)
    assert not ok and reason == "format_invalid"


def test_filename_assertion_is_metadata_conflict():
    lines = _canonical()
    lines.insert(3, "**File**: INVENTED-PART-NAME")
    ok, reason = sls.validate_advisory(lines, _XLSX)
    assert not ok and reason == "metadata_conflict"


def test_size_assertion_is_metadata_conflict():
    lines = _canonical("This spreadsheet is about 38 KB in size.")
    ok, reason = sls.validate_advisory(lines, _XLSX)
    assert not ok and reason == "metadata_conflict"


def test_wrong_type_token_is_metadata_conflict():
    # deterministic ext is xlsx (excel family); claiming it is a PDF contradicts the metadata
    lines = _canonical("This PDF contains the order tracker.")
    ok, reason = sls.validate_advisory(lines, _XLSX)
    assert not ok and reason == "metadata_conflict"


def test_consistent_type_token_passes():
    # 'spreadsheet' is consistent with an xlsx (excel family) — must NOT be rejected
    lines = _canonical("This spreadsheet tracks electrical component orders.")
    ok, reason = sls.validate_advisory(lines, _XLSX)
    assert ok and reason == "ok"


def test_duplicate_summary_heading_is_noncanonical():
    lines = _canonical()
    lines += ["", "### Summary", "a second, duplicate summary section"]
    ok, reason = sls.validate_advisory(lines, _PDF)
    assert not ok and reason == "noncanonical_shape"


def test_extra_noncanonical_heading_is_rejected():
    lines = _canonical()
    lines += ["", "### Actions Needed", "- do a thing"]
    ok, reason = sls.validate_advisory(lines, _PDF)
    assert not ok and reason == "noncanonical_shape"


def test_duplicate_advisory_preamble_is_noncanonical():
    lines = _canonical()
    lines.insert(1, "_Advisory — a second stray preamble._")
    ok, reason = sls.validate_advisory(lines, _PDF)
    assert not ok and reason == "noncanonical_shape"


def test_stray_emphasized_pseudo_header_is_noncanonical():
    lines = _canonical()
    lines.insert(2, "_Advisory Summary_")  # the observed bad-shape header
    ok, reason = sls.validate_advisory(lines, _PDF)
    assert not ok and reason == "noncanonical_shape"


def test_bold_label_line_is_noncanonical():
    lines = _canonical()
    lines.append("**Description**: an order tracking report")
    ok, reason = sls.validate_advisory(lines, _PDF)
    assert not ok and reason == "noncanonical_shape"


def test_the_observed_bad_output_is_rejected():
    # The exact failure class from the live xlsx card: invented file + size + noncanonical shape.
    lines = ["**File**: INVENTED-PART-NAME", "", "**Size**: 38 KB", "",
             "**Description**: an order tracking report for electrical components."]
    ok, reason = sls.validate_advisory(lines, _XLSX)
    assert not ok and reason == "metadata_conflict"
