"""Phase 08A local-first second-brain runtime package.

Prompt 02 landed the read-only contract loader for the V26 second-brain schema.
Prompt 03 adds the runtime config surface and the mock/live Claude adapter
boundary (config receipts written to the V26 table). Remaining runtime builders
(retrieval, query tools, chat/memory, daily brief, gates) arrive in later 08A
prompts. No external API access, no writeback, no raw content.
"""

from __future__ import annotations

from .agents import (
    AgentDefinition,
    AgentRegistry,
    AgentResult,
    AgentRunReceipt,
    build_agent_model_profile_proof,
    build_agent_registry_proof,
    build_agent_tool_policy_proof,
    load_agent_registry,
    validate_agent_registry,
    validate_model_profiles,
)
from .automation_executor import (
    AutomationExecutor,
    ExecutionResult,
    StageReceipt,
    build_automation_execution_proof,
    build_duplicate_prevention_proof,
    build_first_run_after_wake_proof,
    build_retry_backoff_execution_proof,
    build_safe_replay_execution_proof,
    build_weekend_catchup_proof,
    run_automation_execution,
)
from .config import SecondBrainConfig, load_second_brain_config
from .contracts import (
    PHASE_08A_CONTRACT_FILES,
    load_all_phase_08a_contracts,
    load_phase_08a_contract,
)
from .daily_brief import (
    AttentionItemCard,
    DailyBriefContext,
    DailyBriefResult,
    DeliveryHandoffInput,
    DeliveryHandoffPayload,
    HtmlRenderingData,
    LaunchdSchedulePreview,
    MeetingCard,
    NotificationSummary,
    ProjectCard,
    ReviewLoadStatus,
    ReviewRequiredCard,
    ReviewTriageAgent,
    WarningCard,
    build_daily_brief_agent_proof,
    build_daily_brief_context,
    build_daily_brief_context_builder_proof,
    build_daily_brief_delivery_handoff_proof,
    build_daily_brief_schedule_preview,
    build_launchd_schedule_proof,
    build_review_load_status,
    build_review_triage_agent_proof,
    read_latest_daily_brief_runs,
    read_latest_launchd_schedule_previews,
    run_daily_brief,
    validate_daily_brief_policy,
    write_daily_brief_run,
    write_launchd_schedule_preview,
)
from .data_quality import (
    build_phase_08a_gates_proof,
    evaluate_phase_08a_data_quality_gates,
)
from .memory import (
    MemoryCandidate,
    MemoryItem,
    OperatorPreference,
    QualitySignal,
    apply_operator_preferences,
    build_long_term_memory_proof,
    build_memory_curator_agent_proof,
    build_operator_preference_proof,
    capture_preference,
    classify_memory_tier,
    propose_memory_candidate,
    review_memory_candidate,
    validate_memory_policy,
)
from .obsidian_index import (
    ObsidianIndexEntry,
    ObsidianIndexManifest,
    build_approved_obsidian_index_proof,
    build_index,
    list_approved_obsidian_index_entries,
)
from .query_tools import (
    ALLOWLISTED_QUERY_TOOLS,
    QueryToolError,
    QueryToolReceipt,
    QueryToolResult,
    build_sqlite_query_tool_proof,
    list_query_tools,
    read_only_connection,
    run_query_tool,
    validate_query_tool_policy,
)
from .reasoning import (
    AdapterResult,
    AnthropicUnavailable,
    ClaudeAdapter,
    ContextEnvelope,
    LiveClaudeAdapter,
    MockClaudeAdapter,
    ModelCallReceipt,
    build_claude_adapter,
    build_claude_adapter_mock_proof,
    build_model_call_receipt,
)
from .research import (
    OrchestratorResult,
    ResearchPacket,
    ResearchPacketAssessment,
    RetrievalOrchestrator,
    build_research_packet,
    build_research_packet_agent_proof,
    build_retrieval_orchestrator_proof,
    requires_research_packet,
    validate_research_packet_policy,
)
from .retrieval import (
    RetrievalBroker,
    RetrievalEnvelope,
    RetrievalItem,
    build_retrieval_broker_agent_proof,
    validate_retrieval_policy,
)
from .safety import build_second_brain_no_writeback_proof
from .store import read_latest_config_receipt, write_config_receipt
from .synthesis import (
    EvaluationPreview,
    QueryResult,
    build_answer_synthesis_agent_proof,
    build_evaluation_preview,
    build_output_evaluation_agent_proof,
    read_latest_evaluation_runs,
    synthesize_answer,
    write_evaluation_run,
)

__all__ = [
    "AgentDefinition",
    "AgentRegistry",
    "AgentResult",
    "AgentRunReceipt",
    "build_agent_model_profile_proof",
    "build_agent_registry_proof",
    "build_agent_tool_policy_proof",
    "load_agent_registry",
    "validate_agent_registry",
    "validate_model_profiles",
    "PHASE_08A_CONTRACT_FILES",
    "load_all_phase_08a_contracts",
    "load_phase_08a_contract",
    "SecondBrainConfig",
    "load_second_brain_config",
    "AttentionItemCard",
    "DailyBriefContext",
    "DailyBriefResult",
    "DeliveryHandoffInput",
    "DeliveryHandoffPayload",
    "HtmlRenderingData",
    "LaunchdSchedulePreview",
    "MeetingCard",
    "NotificationSummary",
    "ProjectCard",
    "ReviewLoadStatus",
    "ReviewRequiredCard",
    "ReviewTriageAgent",
    "WarningCard",
    "build_daily_brief_agent_proof",
    "build_daily_brief_context",
    "build_daily_brief_context_builder_proof",
    "build_daily_brief_delivery_handoff_proof",
    "build_daily_brief_schedule_preview",
    "build_launchd_schedule_proof",
    "build_phase_08a_gates_proof",
    "evaluate_phase_08a_data_quality_gates",
    "build_review_load_status",
    "build_review_triage_agent_proof",
    "read_latest_daily_brief_runs",
    "read_latest_launchd_schedule_previews",
    "run_daily_brief",
    "validate_daily_brief_policy",
    "write_daily_brief_run",
    "write_launchd_schedule_preview",
    "AdapterResult",
    "AnthropicUnavailable",
    "ClaudeAdapter",
    "ContextEnvelope",
    "LiveClaudeAdapter",
    "MockClaudeAdapter",
    "ModelCallReceipt",
    "build_claude_adapter",
    "build_claude_adapter_mock_proof",
    "build_model_call_receipt",
    "ALLOWLISTED_QUERY_TOOLS",
    "QueryToolError",
    "QueryToolReceipt",
    "QueryToolResult",
    "build_sqlite_query_tool_proof",
    "list_query_tools",
    "read_only_connection",
    "run_query_tool",
    "validate_query_tool_policy",
    "OrchestratorResult",
    "ResearchPacket",
    "ResearchPacketAssessment",
    "RetrievalOrchestrator",
    "build_research_packet",
    "build_research_packet_agent_proof",
    "build_retrieval_orchestrator_proof",
    "requires_research_packet",
    "validate_research_packet_policy",
    "RetrievalBroker",
    "RetrievalEnvelope",
    "RetrievalItem",
    "build_retrieval_broker_agent_proof",
    "validate_retrieval_policy",
    "ObsidianIndexEntry",
    "ObsidianIndexManifest",
    "build_approved_obsidian_index_proof",
    "build_index",
    "list_approved_obsidian_index_entries",
    "read_latest_config_receipt",
    "write_config_receipt",
    "EvaluationPreview",
    "QueryResult",
    "build_answer_synthesis_agent_proof",
    "build_evaluation_preview",
    "build_output_evaluation_agent_proof",
    "read_latest_evaluation_runs",
    "synthesize_answer",
    "write_evaluation_run",
    "build_second_brain_no_writeback_proof",
    "MemoryCandidate",
    "MemoryItem",
    "OperatorPreference",
    "QualitySignal",
    "apply_operator_preferences",
    "build_long_term_memory_proof",
    "build_memory_curator_agent_proof",
    "build_operator_preference_proof",
    "capture_preference",
    "classify_memory_tier",
    "propose_memory_candidate",
    "review_memory_candidate",
    "validate_memory_policy",
    # P03 executor service + runner (additive)
    "AutomationExecutor",
    "ExecutionResult",
    "StageReceipt",
    "build_automation_execution_proof",
    "build_duplicate_prevention_proof",
    "build_first_run_after_wake_proof",
    "build_retry_backoff_execution_proof",
    "build_safe_replay_execution_proof",
    "build_weekend_catchup_proof",
    "run_automation_execution",
]
