"""Local-only advisory summary generation for Obsidian source cards (Phase 10B).

Builds an auditable prompt from a deterministic source card + bounded DB excerpt, calls the local
Ollama ``generate_text`` path (model ``qwen2.5:14b``), and sanitizes the model's Markdown so it can be
safely inserted into the card's ``hb-local-summary`` block. Pure/host-local: no network beyond the
local Ollama daemon, no frontier model, no file/DB writes here (the caller does the SHA-gated write).

The deterministic card is authoritative; this output is advisory only and is always bounded/sanitized.
"""

from __future__ import annotations

import re

from hb_assistant.construction.classification.client import OllamaChatClient, OllamaUnavailable

from .source_notes import LOCAL_SUMMARY_BEGIN_PREFIX, LOCAL_SUMMARY_END

LOCAL_SUMMARY_SYSTEM_PROMPT = (
    "You are writing an ADVISORY local summary for a deterministic Obsidian construction source card.\n"
    "Rules:\n"
    "- This is advisory only, NOT authoritative project data.\n"
    "- Do NOT overwrite or contradict the deterministic fields in the card.\n"
    "- Do NOT invent values, statuses, dates, costs, parties, or project records.\n"
    "- Where the card says Unknown / Not detected / no record linked, keep it that way; do not assert "
    "a value the card does not contain.\n"
    "- Treat templates, reference documents, generic spreadsheets, and metadata-only cards as "
    "non-authoritative; be explicit about low confidence.\n"
    "- Use 'Unknown' or 'Not detected' where information is missing.\n"
    "- Output CONCISE Markdown only. No code fences, no HTML comments, no YAML, no tables, no links, "
    "no file paths.\n"
    "Use exactly this shape:\n"
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source before relying on this "
    "summary._\n\n"
    "### Summary\n<2-4 sentences>\n\n"
    "### PM Attention\n- <bullet>\n\n"
    "### Follow-Up Questions\n- <bullet>\n\n"
    "### Limits / Uncertainty\n- <bullet>\n"
)

# Bounds for the advisory body inserted into the card.
_MAX_OUTPUT_CHARS = 4000
_MAX_OUTPUT_LINES = 60
_MAX_TABLE_LINES = 0  # tables are not allowed in the advisory block
# Absolute home/volume/network paths (macOS user dirs, mounted volumes, *nix home) + Windows drives.
# Written via an alternation group so the source never contains a literal home-path substring.
_ABS_PATH_RE = re.compile(r"(?:^|[\s(])/(?:Users|Volumes|home)/|[A-Za-z]:[\\/]")
# A markdown link whose target is NOT http(s) (i.e. a local file/relative link).
_LOCAL_LINK_RE = re.compile(r"\]\(\s*(?!https?://)[^)]+\)")
_FENCE_RE = re.compile(r"^\s*```")
_HR_RE = re.compile(r"^\s*([-*_])\1{2,}\s*$")  # ---, ***, ___ (also YAML frontmatter delimiter)


def _strip_frontmatter(card_text: str) -> str:
    if not card_text.startswith("---"):
        return card_text
    end = card_text.find("\n---", 3)
    if end == -1:
        return card_text
    nl = card_text.find("\n", end + 1)
    return card_text[nl + 1:] if nl != -1 else ""


def _strip_local_summary_block(text: str) -> str:
    lines = text.splitlines()
    out, skip = [], False
    for ln in lines:
        if ln.startswith(LOCAL_SUMMARY_BEGIN_PREFIX):
            skip = True
            continue
        if skip:
            if ln.strip() == LOCAL_SUMMARY_END:
                skip = False
            continue
        out.append(ln)
    return "\n".join(out)


def build_summary_prompt(card_text: str, detail: dict, *, max_input_chars: int) -> str:
    """Auditable prompt: deterministic card body (no frontmatter, no advisory block) + bounded excerpt.

    Never includes the YAML frontmatter (which carries source_path), the external/vault absolute path,
    the full source file, or a raw DB dump. A stored bounded excerpt is appended only when present and
    non-sensitive.
    """
    body = _strip_local_summary_block(_strip_frontmatter(card_text)).strip()
    parts = ["DETERMINISTIC SOURCE CARD (authoritative — do not contradict):", "", body]
    excerpt = str(detail.get("text_excerpt") or "").strip()
    # Sensitive sources store encrypted text (text_vault_ref) with no excerpt → never include text.
    if excerpt and not detail.get("text_vault_ref"):
        parts += ["", "BOUNDED SOURCE EXCERPT (may be noisy; advisory context only):",
                  excerpt[:max(0, int(max_input_chars))]]
    parts += ["", "Write the advisory summary now, following the required shape and rules."]
    return "\n".join(parts)


def sanitize_advisory_markdown(text: str, *, max_chars: int = _MAX_OUTPUT_CHARS,
                               max_lines: int = _MAX_OUTPUT_LINES) -> list[str]:
    """Bound + strip model output so it can never corrupt the card or leak local detail.

    Drops code fences, HTML comments, hb-local-summary markers, YAML/HR delimiters, table rows,
    absolute paths, and local-file markdown links; bounds total length/lines. Returns [] when nothing
    safe remains (the caller then leaves the card unchanged).
    """
    raw = text.replace("\r\n", "\n")[: max_chars * 2]
    kept: list[str] = []
    for ln in raw.split("\n"):
        if _FENCE_RE.match(ln):
            continue
        if "hb-local-summary" in ln or "<!--" in ln or "-->" in ln:
            continue
        if _HR_RE.match(ln):
            continue
        if ln.lstrip().startswith("|"):  # markdown table row — not allowed
            continue
        if _ABS_PATH_RE.search(ln):
            continue
        if _LOCAL_LINK_RE.search(ln):
            continue
        kept.append(ln.rstrip())
        if len(kept) >= max_lines:
            break
    # Trim leading/trailing blank lines.
    while kept and not kept[0].strip():
        kept.pop(0)
    while kept and not kept[-1].strip():
        kept.pop()
    if not kept or not any(s.strip() for s in kept):
        return []
    # Final char bound (truncate the last kept line set to max_chars total).
    out, total = [], 0
    for ln in kept:
        total += len(ln) + 1
        if total > max_chars:
            break
        out.append(ln)
    return out or []


def _reason_from_unavailable(message: str) -> str:
    if "timeout" in message:
        return "timeout"
    if "missing_response" in message or "invalid_envelope" in message:
        return "invalid_response"
    return "ollama_unavailable"


def generate_advisory(client: OllamaChatClient, prompt: str, *,
                      system: str = LOCAL_SUMMARY_SYSTEM_PROMPT,
                      max_chars: int = _MAX_OUTPUT_CHARS,
                      max_lines: int = _MAX_OUTPUT_LINES) -> tuple[list[str] | None, str]:
    """Call local Ollama for advisory Markdown; return (sanitized_lines | None, reason).

    Never raises on model failure: returns ``None`` + a category reason
    (``timeout``/``ollama_unavailable``/``empty_response``/``invalid_response``) so the caller leaves
    the card unchanged.
    """
    try:
        raw = client.generate_text(system=system, prompt=prompt)
    except OllamaUnavailable as exc:
        return None, _reason_from_unavailable(str(exc))
    if not raw or not raw.strip():
        return None, "empty_response"
    lines = sanitize_advisory_markdown(raw, max_chars=max_chars, max_lines=max_lines)
    if not lines:
        return None, "invalid_response"
    return lines, "ok"


# ---- advisory quality gate (Phase 10F; pure/deterministic — never calls a model) -----------------
# The canonical advisory shape mandated by LOCAL_SUMMARY_SYSTEM_PROMPT: one preamble line + exactly
# these four H3 sections, nothing else.
CANONICAL_HEADINGS: tuple[str, ...] = (
    "Summary", "PM Attention", "Follow-Up Questions", "Limits / Uncertainty")
_HEADING_RE = re.compile(r"^\s{0,3}#{1,6}\s+(?P<text>.+?)\s*$")
_ADVISORY_PREAMBLE_RE = re.compile(r"^\s*[_*]+advisory\b", re.IGNORECASE)
_EMPHASIS_ONLY_RE = re.compile(r"^\s*[_*]{1,2}[^_*].*[^_*][_*]{1,2}\s*$")
_BOLD_LABEL_RE = re.compile(r"^\s*\*\*[^*]+\*\*\s*:")
# A line asserting a filename (e.g. "File:", "**Filename**:", "Attachment name =").
_FILENAME_ASSERT_RE = re.compile(
    r"^\s*[*_]*\s*(?:file\s*name|filename|file|attachment\s*name)\s*[*_]*\s*[:=]", re.IGNORECASE)
# Any size/byte figure — deterministic size is authoritative and already on the card.
_SIZE_ASSERT_RE = re.compile(r"\b\d[\d,.]*\s*(?:kib|mib|gib|kb|mb|gb|bytes?)\b", re.IGNORECASE)
# Format/type vocabulary → canonical family, for contradiction detection.
_TYPE_FAMILY: dict[str, str] = {
    "pdf": "pdf",
    "doc": "word", "docx": "word", "word": "word",
    "xls": "excel", "xlsx": "excel", "excel": "excel", "spreadsheet": "excel", "workbook": "excel",
    "ppt": "ppt", "pptx": "ppt", "powerpoint": "ppt",
    "csv": "csv",
}
_TYPE_TOKEN_RE = re.compile(
    r"\b(pdf|docx?|word|xlsx?|excel|spreadsheet|workbook|pptx?|powerpoint|csv)\b", re.IGNORECASE)


def _deterministic_type_family(detail: dict) -> str | None:
    ext = str(detail.get("file_ext") or "").lower().lstrip(".")
    if ext in _TYPE_FAMILY:
        return _TYPE_FAMILY[ext]
    dtype = str(detail.get("document_type") or "").lower()
    for word, fam in _TYPE_FAMILY.items():
        if word in dtype:
            return fam
    return None


def validate_advisory(lines: list[str], detail: dict | None = None) -> tuple[bool, str]:
    """Gate a sanitized advisory against the canonical shape + deterministic metadata.

    Returns ``(ok, reason)``; rejects (ok=False) when the advisory:
      - contradicts deterministic metadata — asserts a filename or a size/byte figure, or names a
        document/format type inconsistent with ``detail`` file_ext/document_type -> ``metadata_conflict``;
      - is missing any of the four canonical headings                            -> ``format_invalid``;
      - has a noncanonical/duplicated shape (extra or repeated headings, >1 advisory preamble, stray
        emphasized pseudo-headers, or bold ``**Label**:`` lines)                 -> ``noncanonical_shape``.
    Pure/deterministic; never calls a model.
    """
    detail = detail or {}
    # --- metadata contradiction (strongest signal first) ---
    fam = _deterministic_type_family(detail)
    for ln in lines:
        if _FILENAME_ASSERT_RE.match(ln) or _SIZE_ASSERT_RE.search(ln):
            return False, "metadata_conflict"
        if fam:
            for tok in _TYPE_TOKEN_RE.findall(ln):
                if _TYPE_FAMILY.get(tok.lower()) not in (None, fam):
                    return False, "metadata_conflict"
    # --- all four canonical headings present ---
    headings = [m.group("text").strip() for ln in lines if (m := _HEADING_RE.match(ln))]
    heading_set = set(headings)
    if any(want not in heading_set for want in CANONICAL_HEADINGS):
        return False, "format_invalid"
    # --- noncanonical / duplicated shape ---
    canonical = set(CANONICAL_HEADINGS)
    if any(h not in canonical for h in headings):
        return False, "noncanonical_shape"                       # extra/renamed heading
    if any(headings.count(want) > 1 for want in CANONICAL_HEADINGS):
        return False, "noncanonical_shape"                       # duplicated heading
    if sum(1 for ln in lines if _ADVISORY_PREAMBLE_RE.match(ln)) > 1:
        return False, "noncanonical_shape"                       # duplicate advisory preamble
    for ln in lines:
        if _BOLD_LABEL_RE.match(ln):
            return False, "noncanonical_shape"                   # bold pseudo-heading (**File**:, ...)
        if _EMPHASIS_ONLY_RE.match(ln) and not _ADVISORY_PREAMBLE_RE.match(ln):
            return False, "noncanonical_shape"                   # stray _Advisory_ / _Advisory Summary_
    return True, "ok"


# =================================================================================================
# Phase 10J summary-quality hardening (source cards): source-grounded, classification-aware,
# five-section summaries with deterministic quality gates. Separate from the four-section
# validate_advisory / LOCAL_SUMMARY_SYSTEM_PROMPT path used by 10B/10F (attachment) summaries.
# =================================================================================================

SOURCE_CARD_HEADINGS: tuple[str, ...] = (
    "Summary", "Key Extracted Details", "PM Attention", "Follow-Up Questions", "Limits / Uncertainty")

SOURCE_CARD_SUMMARY_SYSTEM_PROMPT = (
    "You are writing an ADVISORY second-brain summary of a construction SOURCE DOCUMENT for a project "
    "manager.\n"
    "Ground EVERY statement in the SOURCE EXCERPT and DOCUMENT TITLE provided — not in the card's "
    "classifier label.\n"
    "The CLASSIFIER HINT (document_type) MAY BE WRONG. Identify what the document ACTUALLY is from its "
    "own title/header/content: a generic specification or template, a tracking/value-analysis log, a "
    "transmittal, a memo / clarification / open-questions list, or a project-specific instrument.\n"
    "If the content contradicts the classifier hint, identify the TRUE nature and NOTE THE MISMATCH in "
    "### Limits / Uncertainty; do NOT assert the classifier's label as fact (e.g. do not call a "
    "value-analysis tracking log a 'warranty').\n"
    "Extract concrete specifics from the source: dates, statuses, spec section numbers, line-item "
    "categories, document identifiers, key requirements, and unresolved questions. Mention data/table "
    "quality problems if visible (e.g. #REF errors). If the document is a generic/template "
    "specification, SAY SO and do not claim project-specific tailoring the text does not support.\n"
    "Do NOT invent amounts, statuses, dates, parties, or project-specific facts. Use 'Unknown' or 'Not "
    "stated' where the source is silent.\n"
    "Output CONCISE Markdown only — no code fences, HTML comments, YAML, tables, links, or file paths.\n"
    "Use EXACTLY these five sections, in this order:\n"
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source before relying on this "
    "summary._\n\n"
    "### Summary\n<what the document actually is, why it exists, and whether it is generic/template, a "
    "log/tracker, a transmittal, a memo/questions list, or project-specific>\n\n"
    "### Key Extracted Details\n- <dates / statuses / spec sections / line-item categories / identifiers "
    "/ major requirements / data-quality issues such as #REF>\n\n"
    "### PM Attention\n- <concrete review actions, missing dispositions, values/statuses to verify, "
    "contract/submittal/scope implications>\n\n"
    "### Follow-Up Questions\n- <specific unresolved questions grounded in the source>\n\n"
    "### Limits / Uncertainty\n- <extraction issues, classification mismatch, generic/template status, "
    "truncation, table/OCR risk>\n"
)


def build_source_card_summary_prompt(card_text: str, detail: dict, *, title: str,
                                     document_type: str | None, max_input_chars: int) -> str:
    """Source-grounded prompt: the SOURCE EXCERPT + TITLE are primary; the classifier is a hint."""
    body = _strip_local_summary_block(_strip_frontmatter(card_text)).strip()
    excerpt = str(detail.get("text_excerpt") or "").strip()
    parts = [
        f"DOCUMENT TITLE: {title}",
        f"CLASSIFIER HINT (may be wrong): document_type={document_type or 'unknown'}",
        "",
        "PRIMARY EVIDENCE — SOURCE EXCERPT (ground your summary in the document's own text below):",
    ]
    if excerpt and not detail.get("text_vault_ref"):
        parts.append(excerpt[:max(0, int(max_input_chars))])
    else:
        parts.append("(no source excerpt available — note this in Limits / Uncertainty and keep the "
                     "summary minimal)")
    parts += ["",
              "SECONDARY CONTEXT — deterministic source card (its classifier label may be wrong):",
              "", body, "",
              "Write the five-section advisory now, grounded in the SOURCE EXCERPT and TITLE."]
    return "\n".join(parts)


_SPEC_SECTION_RE = re.compile(r"\b\d\d[\s-]\d\d[\s-]\d\d\b")  # e.g. 02 87 13 / 02-87-13
_GROUND_STOP = frozenset({
    "this", "that", "with", "from", "have", "will", "your", "there", "which", "their", "about",
    "document", "source", "card", "project", "summary", "advisory", "please", "shall", "these",
    "them", "then", "than", "into", "over", "under", "such", "been", "were", "when", "what",
    "unknown", "stated", "none", "detail", "details", "generated", "local", "verify",
})


def _content_tokens(text: str) -> set[str]:
    return {w for w in re.findall(r"[a-z0-9#]{4,}", str(text or "").lower()) if w not in _GROUND_STOP}


def _title_signal(title: str, excerpt: str) -> str | None:
    """Deterministic document-family signal from the title + excerpt header (never body-only guess)."""
    ttok = set(re.sub(r"[^a-z0-9]+", " ", str(title or "").lower()).split())
    head = (str(title or "") + "\n" + str(excerpt or "")[:1200]).lower()
    hnorm = re.sub(r"[^a-z0-9]+", " ", head)
    if ("va" in ttok and ("log" in ttok or "tracking" in ttok)) or "value analysis" in hnorm \
            or "value engineering" in hnorm:
        return "value_analysis_log"
    if _SPEC_SECTION_RE.search(head) or "masterworks" in hnorm or "master works" in hnorm \
            or "specification" in hnorm or "part 1 general" in hnorm or "part 2 products" in hnorm:
        return "specification_generic"
    if re.search(r"clarification|open items|open questions|memorandum|preconstruction question", hnorm) \
            or " memo " in f" {hnorm} " or head.count("?") >= 2:
        return "memo_questions"
    if "transmittal" in hnorm:
        return "transmittal"
    if "warranty" in hnorm or "warrant" in ttok:
        return "warranty"
    if "tracking" in hnorm or "log" in ttok:
        return "tracker"
    return None


# document_type values that CONTRADICT a detected family (surface, don't repair, in this pass).
_FAMILY_CONFLICTS = {
    "value_analysis_log": {"warranty", "contract", "submittal"},
    "specification_generic": {"submittal", "scope_of_work", "warranty", "contract"},
    "memo_questions": {"scope_of_work", "contract", "submittal", "warranty"},
    "transmittal": {"scope_of_work", "contract"},
}
# For a detected family, the summary must satisfy EACH required signal group (>=1 match per group).
_FAMILY_REQUIRED: dict[str, list[str]] = {
    "value_analysis_log": [r"value[- ]?analysis|value engineering|\bva\b|tracking log|value tracking",
                           r"line[- ]?item|status|value|alternate"],
    "specification_generic": [r"generic|template|specification|spec package|standard|master ?works",
                              r"clean|kill|coat|moisture|iicrc|s\s?520|submittal|sds|voc|product|"
                              r"manufacturer|remediation"],
    "memo_questions": [r"clarification|question|open item|preconstruction|unresolved|"
                       r"to be (confirmed|determined)|\bmemo\b"],
}


def detect_classification_conflict(document_type: str | None, title: str, excerpt: str) -> str | None:
    """Return the true document family when title/content contradict document_type, else None."""
    fam = _title_signal(title, excerpt)
    if fam and str(document_type or "").lower() in _FAMILY_CONFLICTS.get(fam, set()):
        return fam
    return None


def _section_bullets(lines: list[str], heading: str) -> list[str]:
    out, cap = [], False
    for ln in lines:
        m = _HEADING_RE.match(ln)
        if m:
            cap = m.group("text").strip() == heading
            continue
        if cap and ln.strip():
            txt = ln.strip().lstrip("-*").strip()
            if txt and txt.lower() not in ("none", "n/a", "not stated", "unknown", "not detected"):
                out.append(txt)
    return out


def validate_summary_quality(lines: list[str], detail: dict | None = None, *, title: str = "",
                             document_type: str | None = None) -> tuple[bool, str]:
    """Strict source-card summary gate: five-section shape + metadata/grounding/classification checks.

    Returns ``(ok, reason)``. Reject reasons: ``metadata_conflict`` (filename/size/type assertion),
    ``format_invalid`` / ``noncanonical_shape`` (five-section shape), ``thin_key_details``,
    ``ungrounded`` (not grounded in the source excerpt), ``classification_conflict`` (parrots a
    contradicted classifier label — e.g. VA log as warranty), ``generic_spec_unqualified``,
    ``missing_data_quality_note`` (excerpt has #REF but summary omits it), and
    ``missing_required_family_signal`` (detected family's required content absent). Pure/deterministic.
    """
    detail = detail or {}
    excerpt = str(detail.get("text_excerpt") or "")
    # 1. metadata contradiction (reuse the four-section path's filename/size/type-family checks)
    fam_type = _deterministic_type_family(detail)
    for ln in lines:
        if _FILENAME_ASSERT_RE.match(ln) or _SIZE_ASSERT_RE.search(ln):
            return False, "metadata_conflict"
        if fam_type:
            for tok in _TYPE_TOKEN_RE.findall(ln):
                if _TYPE_FAMILY.get(tok.lower()) not in (None, fam_type):
                    return False, "metadata_conflict"
    # 2. five-section shape
    headings = [m.group("text").strip() for ln in lines if (m := _HEADING_RE.match(ln))]
    hset = set(headings)
    if any(h not in hset for h in SOURCE_CARD_HEADINGS):
        return False, "format_invalid"
    canon = set(SOURCE_CARD_HEADINGS)
    if any(h not in canon for h in headings) or any(headings.count(h) > 1 for h in SOURCE_CARD_HEADINGS):
        return False, "noncanonical_shape"
    if sum(1 for ln in lines if _ADVISORY_PREAMBLE_RE.match(ln)) > 1:
        return False, "noncanonical_shape"
    if any(_BOLD_LABEL_RE.match(ln) for ln in lines):
        return False, "noncanonical_shape"
    # 3. thin Key Extracted Details
    if not _section_bullets(lines, "Key Extracted Details"):
        return False, "thin_key_details"
    blow = "\n".join(lines).lower()
    # 4. grounding in the source excerpt (skipped only when no excerpt is available)
    if excerpt.strip():
        meta = _content_tokens(f"{title} {document_type}")
        shared = (_content_tokens(excerpt) - meta) & (_content_tokens(blow) - meta)
        if len(shared) < 3:
            return False, "ungrounded"
    fam = _title_signal(title, excerpt)
    # 5. classification conflict — must not parrot a contradicted label (VA log summarized as warranty)
    if fam == "value_analysis_log" and re.search(r"warrant", blow) and not re.search(
            r"value[- ]?analysis|value engineering|\bva\b|tracking log|value tracking", blow):
        return False, "classification_conflict"
    # 6. generic-spec must be qualified as generic/template (not a bare project-specific submittal)
    if fam == "specification_generic":
        if not re.search(r"generic|template|specification|spec package|standard|master ?works", blow):
            return False, "generic_spec_unqualified"
        if re.search(r"project[- ]specific submittal", blow) and not re.search(r"generic|template", blow):
            return False, "generic_spec_unqualified"
    # 7. table/data-quality — surface #REF when the excerpt contains it
    if "#ref" in excerpt.lower() and "#ref" not in blow \
            and not re.search(r"\bref\b|table|data[- ]quality|value verification", blow):
        return False, "missing_data_quality_note"
    # 8. required family signals (each group must have >=1 match)
    for pattern in _FAMILY_REQUIRED.get(fam or "", []):
        if not re.search(pattern, blow):
            return False, "missing_required_family_signal"
    return True, "ok"
