"""Local-only advisory summary generation for Obsidian source cards (Phase 10B).

Builds an auditable prompt from a deterministic source card + bounded DB excerpt, calls the local
Ollama ``generate_text`` path (model ``qwen2.5:14b``), and sanitizes the model's Markdown so it can be
safely inserted into the card's ``hb-local-summary`` block. Pure/host-local: no network beyond the
local Ollama daemon, no frontier model, no file/DB writes here (the caller does the SHA-gated write).

The deterministic card is authoritative; this output is advisory only and is always bounded/sanitized.
"""

from __future__ import annotations

import re

from hb_assistant.construction.classification.client import OllamaChatClient, OllamaUnavailable

from .source_notes import LOCAL_SUMMARY_BEGIN_PREFIX, LOCAL_SUMMARY_END

LOCAL_SUMMARY_SYSTEM_PROMPT = (
    "You are writing an ADVISORY local summary for a deterministic Obsidian construction source card.\n"
    "Rules:\n"
    "- This is advisory only, NOT authoritative project data.\n"
    "- Do NOT overwrite or contradict the deterministic fields in the card.\n"
    "- Do NOT invent values, statuses, dates, costs, parties, or project records.\n"
    "- Where the card says Unknown / Not detected / no record linked, keep it that way; do not assert "
    "a value the card does not contain.\n"
    "- Treat templates, reference documents, generic spreadsheets, and metadata-only cards as "
    "non-authoritative; be explicit about low confidence.\n"
    "- Use 'Unknown' or 'Not detected' where information is missing.\n"
    "- Output CONCISE Markdown only. No code fences, no HTML comments, no YAML, no tables, no links, "
    "no file paths.\n"
    "Use exactly this shape:\n"
    "_Advisory — locally generated by qwen2.5:14b. Verify against the source before relying on this "
    "summary._\n\n"
    "### Summary\n<2-4 sentences>\n\n"
    "### PM Attention\n- <bullet>\n\n"
    "### Follow-Up Questions\n- <bullet>\n\n"
    "### Limits / Uncertainty\n- <bullet>\n"
)

# Bounds for the advisory body inserted into the card.
_MAX_OUTPUT_CHARS = 4000
_MAX_OUTPUT_LINES = 60
_MAX_TABLE_LINES = 0  # tables are not allowed in the advisory block
# Absolute home/volume/network paths (macOS user dirs, mounted volumes, *nix home) + Windows drives.
# Written via an alternation group so the source never contains a literal home-path substring.
_ABS_PATH_RE = re.compile(r"(?:^|[\s(])/(?:Users|Volumes|home)/|[A-Za-z]:[\\/]")
# A markdown link whose target is NOT http(s) (i.e. a local file/relative link).
_LOCAL_LINK_RE = re.compile(r"\]\(\s*(?!https?://)[^)]+\)")
_FENCE_RE = re.compile(r"^\s*```")
_HR_RE = re.compile(r"^\s*([-*_])\1{2,}\s*$")  # ---, ***, ___ (also YAML frontmatter delimiter)


def _strip_frontmatter(card_text: str) -> str:
    if not card_text.startswith("---"):
        return card_text
    end = card_text.find("\n---", 3)
    if end == -1:
        return card_text
    nl = card_text.find("\n", end + 1)
    return card_text[nl + 1:] if nl != -1 else ""


def _strip_local_summary_block(text: str) -> str:
    lines = text.splitlines()
    out, skip = [], False
    for ln in lines:
        if ln.startswith(LOCAL_SUMMARY_BEGIN_PREFIX):
            skip = True
            continue
        if skip:
            if ln.strip() == LOCAL_SUMMARY_END:
                skip = False
            continue
        out.append(ln)
    return "\n".join(out)


def build_summary_prompt(card_text: str, detail: dict, *, max_input_chars: int) -> str:
    """Auditable prompt: deterministic card body (no frontmatter, no advisory block) + bounded excerpt.

    Never includes the YAML frontmatter (which carries source_path), the external/vault absolute path,
    the full source file, or a raw DB dump. A stored bounded excerpt is appended only when present and
    non-sensitive.
    """
    body = _strip_local_summary_block(_strip_frontmatter(card_text)).strip()
    parts = ["DETERMINISTIC SOURCE CARD (authoritative — do not contradict):", "", body]
    excerpt = str(detail.get("text_excerpt") or "").strip()
    # Sensitive sources store encrypted text (text_vault_ref) with no excerpt → never include text.
    if excerpt and not detail.get("text_vault_ref"):
        parts += ["", "BOUNDED SOURCE EXCERPT (may be noisy; advisory context only):",
                  excerpt[:max(0, int(max_input_chars))]]
    parts += ["", "Write the advisory summary now, following the required shape and rules."]
    return "\n".join(parts)


def sanitize_advisory_markdown(text: str, *, max_chars: int = _MAX_OUTPUT_CHARS,
                               max_lines: int = _MAX_OUTPUT_LINES) -> list[str]:
    """Bound + strip model output so it can never corrupt the card or leak local detail.

    Drops code fences, HTML comments, hb-local-summary markers, YAML/HR delimiters, table rows,
    absolute paths, and local-file markdown links; bounds total length/lines. Returns [] when nothing
    safe remains (the caller then leaves the card unchanged).
    """
    raw = text.replace("\r\n", "\n")[: max_chars * 2]
    kept: list[str] = []
    for ln in raw.split("\n"):
        if _FENCE_RE.match(ln):
            continue
        if "hb-local-summary" in ln or "<!--" in ln or "-->" in ln:
            continue
        if _HR_RE.match(ln):
            continue
        if ln.lstrip().startswith("|"):  # markdown table row — not allowed
            continue
        if _ABS_PATH_RE.search(ln):
            continue
        if _LOCAL_LINK_RE.search(ln):
            continue
        kept.append(ln.rstrip())
        if len(kept) >= max_lines:
            break
    # Trim leading/trailing blank lines.
    while kept and not kept[0].strip():
        kept.pop(0)
    while kept and not kept[-1].strip():
        kept.pop()
    if not kept or not any(s.strip() for s in kept):
        return []
    # Final char bound (truncate the last kept line set to max_chars total).
    out, total = [], 0
    for ln in kept:
        total += len(ln) + 1
        if total > max_chars:
            break
        out.append(ln)
    return out or []


def _reason_from_unavailable(message: str) -> str:
    if "timeout" in message:
        return "timeout"
    if "missing_response" in message or "invalid_envelope" in message:
        return "invalid_response"
    return "ollama_unavailable"


def generate_advisory(client: OllamaChatClient, prompt: str, *,
                      system: str = LOCAL_SUMMARY_SYSTEM_PROMPT,
                      max_chars: int = _MAX_OUTPUT_CHARS,
                      max_lines: int = _MAX_OUTPUT_LINES) -> tuple[list[str] | None, str]:
    """Call local Ollama for advisory Markdown; return (sanitized_lines | None, reason).

    Never raises on model failure: returns ``None`` + a category reason
    (``timeout``/``ollama_unavailable``/``empty_response``/``invalid_response``) so the caller leaves
    the card unchanged.
    """
    try:
        raw = client.generate_text(system=system, prompt=prompt)
    except OllamaUnavailable as exc:
        return None, _reason_from_unavailable(str(exc))
    if not raw or not raw.strip():
        return None, "empty_response"
    lines = sanitize_advisory_markdown(raw, max_chars=max_chars, max_lines=max_lines)
    if not lines:
        return None, "invalid_response"
    return lines, "ok"
