"""Prompt Preflight — WORKFLOW recipes (durable routing source, seeded as static data).

Each workflow is an ordered tool recipe for a common connected-client intent, with the authorization,
retrieval-budget, provenance, and fallback fields the route engine needs. Generation workflows reference the
real N8C-24 ``pa_output_*`` tools; canonical promotion references the N8C-23 ``pa_artifact_*`` tools. Nothing
here executes — the preflight only *recommends* a recipe. Organization-neutral.
"""

from __future__ import annotations

from typing import Any

# write_risk vocabulary: none / staged_write / canonical_write / archive_move.
# action_class vocabulary (authorization): read / staged_write / canonical_promotion / archive.


def _w(**kw: Any) -> dict[str, Any]:
    base: dict[str, Any] = {
        "workflow_id": "", "family_id": "", "trigger_phrases": [], "intent_classes": [],
        "when_to_use": "", "when_not_to_use": "", "tool_sequence": [], "required_inputs": [],
        "optional_inputs": [], "operator_authorization_policy": "read", "additional_approval_points": [],
        "write_risk": "none", "default_retrieval_layer": "route_only", "max_default_candidates": 10,
        "max_default_chars": 4000, "expected_outputs": [], "required_provenance": [], "must_not_use": [],
        "fallback_rules": [], "failure_recovery": "",
    }
    base.update(kw)
    return base


WORKFLOWS: list[dict[str, Any]] = [
    # ---- status / discovery / routing ----
    _w(workflow_id="status_check", family_id="status_health",
       trigger_phrases=["status", "is the server up", "health", "capability mode", "what mode"],
       intent_classes=["status"], when_to_use="Operator asks whether the server/tools/queues are healthy.",
       when_not_to_use="Any content retrieval or write.", tool_sequence=["hb_mcp_status"],
       expected_outputs=["capability + gate + queue status"],
       must_not_use=["treating status as source-of-truth content"]),
    _w(workflow_id="tool_help_lookup", family_id="tool_catalog_help_query",
       trigger_phrases=["what tools", "which tool", "how do I use", "what can you do"],
       intent_classes=["discovery"], when_to_use="Operator asks which tool to use / how to call it.",
       when_not_to_use="You already know the tool.",
       tool_sequence=["hb_assistant_catalog", "hb_assistant_tool_help"],
       expected_outputs=["tool catalog + per-tool help"]),
    _w(workflow_id="context_preflight", family_id="prompt_routing",
       trigger_phrases=["what should I do with", "route this", "how should I handle"],
       intent_classes=["routing"], when_to_use="Decide intent → family → workflow → tools before acting.",
       when_not_to_use="You already have a confident single-tool route.",
       tool_sequence=["pa_prompt_route"], expected_outputs=["route plan (read-only)"],
       must_not_use=["staging/writing/promoting/committing anything from the preflight"]),
    _w(workflow_id="prompt_route", family_id="prompt_routing",
       trigger_phrases=["explain the route", "why that tool"], intent_classes=["routing"],
       when_to_use="Explain a route decision.", when_not_to_use="Executing an action.",
       tool_sequence=["pa_prompt_route_explain"], expected_outputs=["route rationale"]),
    _w(workflow_id="manifest_lookup", family_id="client_tool_manifest",
       trigger_phrases=["tool manifest", "operating manifest"], intent_classes=["discovery"],
       when_to_use="Read the versioned tool operating manifest.", when_not_to_use="Routing a task.",
       tool_sequence=["pa_tool_manifest_get"], expected_outputs=["manifest record"]),
    _w(workflow_id="manifest_freshness_check", family_id="client_tool_manifest",
       trigger_phrases=["is the manifest current", "manifest freshness"], intent_classes=["discovery"],
       when_to_use="Check whether the manifest drifted from the live surface.", when_not_to_use="",
       tool_sequence=["pa_tool_manifest_freshness_check", "pa_tool_surface_freshness_check"],
       expected_outputs=["freshness/staleness state"]),
    # ---- read / retrieval ----
    _w(workflow_id="source_file_search", family_id="assistant_source_connector",
       trigger_phrases=["find the source", "find the file", "locate", "where is the document"],
       intent_classes=["retrieval", "discovery"],
       when_to_use="Locate a source file by name/topic before reading it.",
       when_not_to_use="You already have the exact card/source id.",
       tool_sequence=["assistant_source_file_search", "assistant_source_file_metadata"],
       required_inputs=["query"], default_retrieval_layer="metadata_discovery",
       expected_outputs=["candidate source list (bounded)"], required_provenance=["source_id"],
       fallback_rules=["if no semantic hit, fall back to hb_root_search (legacy, low-level)"],
       must_not_use=["reading full file bodies before candidate triage"]),
    _w(workflow_id="source_file_metadata_review", family_id="assistant_navigation",
       trigger_phrases=["metadata for", "details about the source"], intent_classes=["retrieval"],
       when_to_use="Inspect source/card metadata before a bounded read.", when_not_to_use="",
       tool_sequence=["assistant_source_file_metadata"], default_retrieval_layer="metadata_discovery",
       required_provenance=["source_id"]),
    _w(workflow_id="source_file_bounded_read", family_id="assistant_navigation",
       trigger_phrases=["read the source", "open and read"], intent_classes=["retrieval"],
       when_to_use="Bounded read once the exact source id/filename is known.",
       when_not_to_use="Broad/ambiguous ask — triage candidates first.",
       tool_sequence=["assistant_source_file_read"], required_inputs=["source_id"],
       default_retrieval_layer="bounded_read", max_default_chars=4000, required_provenance=["source_id"]),
    _w(workflow_id="context_pack_retrieval", family_id="assistant_context_packs",
       trigger_phrases=["assemble context", "context pack", "what do we know", "background on"],
       intent_classes=["retrieval"], when_to_use="Assemble a durable context pack for a topic.",
       when_not_to_use="Single exact-id lookup.",
       tool_sequence=["assistant_get_context_pack"], default_retrieval_layer="candidate_triage",
       required_provenance=["source_id"]),
    _w(workflow_id="canonical_decision_retrieval", family_id="assistant_decision_memory",
       trigger_phrases=["what did we decide", "the decision on", "was it decided"],
       intent_classes=["retrieval"], when_to_use="Retrieve a canonical decision record.",
       when_not_to_use="Free-text source search.",
       tool_sequence=["assistant_get_decision"], required_provenance=["source_id", "decision_id"],
       fallback_rules=["if no canonical decision, fall back to source search — clearly labeled non-canonical"]),
    _w(workflow_id="canonical_preference_retrieval", family_id="assistant_decision_memory",
       trigger_phrases=["standing preference", "how do we usually", "the preference for"],
       intent_classes=["retrieval"], when_to_use="Retrieve a standing preference.", when_not_to_use="",
       tool_sequence=["assistant_get_preference"], required_provenance=["source_id"]),
    _w(workflow_id="canonical_open_loop_retrieval", family_id="assistant_decision_memory",
       trigger_phrases=["open loops", "what is pending", "unresolved"], intent_classes=["retrieval"],
       when_to_use="List open loops / unresolved threads.", when_not_to_use="",
       tool_sequence=["assistant_list_open_loops"], required_provenance=["source_id"]),
    _w(workflow_id="quality_findings_review", family_id="assistant_quality",
       trigger_phrases=["quality findings", "what needs review", "review queue"],
       intent_classes=["retrieval"], when_to_use="Review advisory quality findings / review queue.",
       when_not_to_use="Writing a disposition.", tool_sequence=["assistant_get_review_summary"],
       must_not_use=["repairing or rebuilding from a client"]),
    _w(workflow_id="feedback_review", family_id="assistant_feedback",
       trigger_phrases=["feedback", "recommendations"], intent_classes=["retrieval"],
       when_to_use="Read feedback-loop recommendations (advisory).", when_not_to_use="",
       tool_sequence=["assistant_get_feedback"]),
    _w(workflow_id="action_stage_review", family_id="assistant_action_stages",
       trigger_phrases=["staged actions", "action stage"], intent_classes=["retrieval"],
       when_to_use="Inspect staged actions (staging is not execution).",
       when_not_to_use="Executing/sending anything.", tool_sequence=["assistant_get_action_stage"],
       must_not_use=["executing staged actions; no send/email/calendar"]),
    # ---- artifact workspace (session capture → staged canonical) ----
    _w(workflow_id="document_session", family_id="artifact_workspace",
       trigger_phrases=["document this session", "capture this", "remember this", "save to memory",
                        "write this down", "log our decisions"],
       intent_classes=["capture", "staged_write"],
       when_to_use="Capture a session's decisions/preferences/open-loops as staged artifact proposals.",
       when_not_to_use="Generating a work-product file (use client_output_workspace).",
       tool_sequence=["pa_session_capture_stage", "pa_artifact_proposal_stage",
                      "pa_artifact_proposal_review"],
       required_inputs=["session_summary"], operator_authorization_policy="staged_write",
       write_risk="staged_write",
       additional_approval_points=["canonical promotion needs a separate server-minted approval"],
       expected_outputs=["staged artifact proposals (nothing written to the vault yet)"],
       required_provenance=["session_capture_id"],
       must_not_use=["writing the vault directly", "promoting without explicit approval"],
       fallback_rules=["never fall back to hb_output_write_file or a raw vault write"]),
    _w(workflow_id="stage_artifact_proposals", family_id="artifact_workspace",
       trigger_phrases=["stage proposals", "prepare memory records"], intent_classes=["staged_write"],
       when_to_use="Stage artifact proposals from an existing capture.", when_not_to_use="",
       tool_sequence=["pa_artifact_proposal_stage"], operator_authorization_policy="staged_write",
       write_risk="staged_write", required_provenance=["session_capture_id"]),
    _w(workflow_id="review_artifact_proposals", family_id="artifact_workspace",
       trigger_phrases=["review proposals", "show staged memory"], intent_classes=["retrieval"],
       when_to_use="Review staged proposals before promotion.", when_not_to_use="",
       tool_sequence=["pa_artifact_proposal_list", "pa_artifact_proposal_get",
                      "pa_artifact_proposal_compare"]),
    _w(workflow_id="revise_artifact_proposal", family_id="artifact_workspace",
       trigger_phrases=["revise the proposal", "edit the staged memory"], intent_classes=["staged_write"],
       when_to_use="Revise a staged proposal before promotion.", when_not_to_use="",
       tool_sequence=["pa_artifact_proposal_revise"], operator_authorization_policy="staged_write",
       write_risk="staged_write"),
    # ---- canonical promotion ----
    _w(workflow_id="plan_canonical_promotion", family_id="canonical_promotion",
       trigger_phrases=["plan promotion", "prepare to promote"], intent_classes=["retrieval"],
       when_to_use="Plan a canonical promotion (still no write).", when_not_to_use="",
       tool_sequence=["pa_artifact_proposal_plan_promotion"]),
    _w(workflow_id="validate_canonical_promotion", family_id="canonical_promotion",
       trigger_phrases=["validate promotion"], intent_classes=["retrieval"],
       when_to_use="Validate a planned promotion + mint approval.", when_not_to_use="",
       tool_sequence=["pa_artifact_promotion_validate"],
       expected_outputs=["validation result + server-minted approval id"]),
    _w(workflow_id="apply_canonical_promotion", family_id="canonical_promotion",
       trigger_phrases=["promote", "make canonical", "finalize the decision record", "apply promotion"],
       intent_classes=["canonical_promotion"],
       when_to_use="Apply an approved canonical promotion to Obsidian cards.",
       when_not_to_use="Ordinary file export (use client_output_workspace).",
       tool_sequence=["pa_artifact_promotion_apply"],
       required_inputs=["operator_approval_id"], operator_authorization_policy="canonical_promotion",
       write_risk="canonical_write",
       additional_approval_points=["requires server-minted approval id + prior validation"],
       required_provenance=["proposal_id", "operator_approval_id"],
       must_not_use=["inventing an approval id", "a broad vault write"],
       fallback_rules=["never fall back to a raw vault write on failure"],
       failure_recovery="On stale tool surface or approval mismatch, fail closed and re-validate."),
    _w(workflow_id="inspect_promotion_receipt", family_id="canonical_promotion",
       trigger_phrases=["promotion receipt", "was it promoted"], intent_classes=["retrieval"],
       when_to_use="Inspect a promotion receipt/manifest.", when_not_to_use="",
       tool_sequence=["pa_artifact_promotion_receipt_get", "pa_artifact_manifest_get"]),
    # ---- generated file output workspace (N8C-24) ----
    _w(workflow_id="generate_docx_output", family_id="client_output_workspace",
       trigger_phrases=["generate a word doc", "make a word document", "save this as docx",
                        "write a report and save it"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a DOCX work-product file and save it to the outputs root.",
       when_not_to_use="Canonical memory or an Obsidian note.",
       tool_sequence=["pa_output_stage", "pa_output_commit"],
       required_inputs=["title", "content", "content_mode"], operator_authorization_policy="staged_write",
       write_risk="staged_write",
       additional_approval_points=["commit requires the server-minted approval id from staging"],
       expected_outputs=["committed DOCX under the outputs root + receipt + manifest entry"],
       required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["writing to the Obsidian vault", "canonical promotion",
                     "the legacy hb_output_write_file scratch writer"],
       fallback_rules=["never fall back to hb_output_write_file"],
       failure_recovery="On hash drift/stale surface, fail closed; re-stage a new version."),
    _w(workflow_id="generate_xlsx_output", family_id="client_output_workspace",
       trigger_phrases=["make a spreadsheet", "excel file", "save as xlsx", "export to excel"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce an XLSX from CSV/tabular content.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["the legacy hb_output_write_file scratch writer"]),
    _w(workflow_id="generate_pdf_output", family_id="client_output_workspace",
       trigger_phrases=["make a pdf", "save as pdf", "generate a pdf report"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a PDF (reportlab) from markdown/text/html.",
       when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"],
       expected_outputs=["committed PDF (basic Platypus layout) + receipt"]),
    _w(workflow_id="generate_pptx_output", family_id="client_output_workspace",
       trigger_phrases=["make a powerpoint", "slide deck", "save as pptx"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a PPTX from markdown/json.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"]),
    _w(workflow_id="generate_markdown_output", family_id="client_output_workspace",
       trigger_phrases=["save as markdown", "make a markdown file", "export notes as md"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a standalone markdown FILE (not a vault note).",
       when_not_to_use="Canonical memory / an Obsidian note — those are different surfaces.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["confusing a generated .md file with an Obsidian vault note"]),
    _w(workflow_id="generate_csv_output", family_id="client_output_workspace",
       trigger_phrases=["save as csv", "export to csv"], intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a CSV file.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"]),
    _w(workflow_id="generate_json_output", family_id="client_output_workspace",
       trigger_phrases=["save as json", "export json"], intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a JSON file.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"]),
    _w(workflow_id="generate_html_output", family_id="client_output_workspace",
       trigger_phrases=["save as html", "export html"], intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce an HTML file.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"]),
    _w(workflow_id="generate_zip_package", family_id="client_output_workspace",
       trigger_phrases=["make a zip", "bundle these files", "zip package", "export as zip"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Assemble a validated ZIP (from base64 or already-committed outputs).",
       when_not_to_use="Canonical memory; anything requiring extraction.",
       tool_sequence=["pa_output_stage", "pa_output_zip_inspect", "pa_output_commit"],
       required_inputs=["title", "content"], operator_authorization_policy="staged_write",
       write_risk="staged_write", required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["extracting a ZIP", "executable/script members", "traversal/absolute member paths"],
       fallback_rules=["a ZIP that fails validation is never written"]),
    # ---- output receipts / manifest / archive ----
    _w(workflow_id="list_generated_outputs", family_id="output_receipts_manifests",
       trigger_phrases=["list outputs", "what files did I generate", "show generated files"],
       intent_classes=["retrieval"], when_to_use="List generated outputs.", when_not_to_use="",
       tool_sequence=["pa_output_list"], default_retrieval_layer="metadata_discovery"),
    _w(workflow_id="inspect_generated_output_metadata", family_id="output_receipts_manifests",
       trigger_phrases=["details on the output", "output metadata", "where did the file go"],
       intent_classes=["retrieval"], when_to_use="Inspect one generated output's metadata.",
       when_not_to_use="", tool_sequence=["pa_output_metadata", "pa_output_read_excerpt"],
       default_retrieval_layer="metadata_discovery"),
    _w(workflow_id="retrieve_generated_output_receipt", family_id="output_receipts_manifests",
       trigger_phrases=["output receipt", "receipt for the file", "output manifest"],
       intent_classes=["retrieval"], when_to_use="Retrieve an output receipt/manifest.",
       when_not_to_use="", tool_sequence=["pa_output_receipt_get", "pa_output_manifest_get"]),
    _w(workflow_id="archive_generated_output", family_id="output_receipts_manifests",
       trigger_phrases=["archive the output", "move the file to archive"],
       intent_classes=["archive", "staged_write"],
       when_to_use="Archive a committed output (staged plan → approved move; never delete).",
       when_not_to_use="Deleting a file (deletion is not offered).",
       tool_sequence=["pa_output_archive_plan", "pa_output_archive_commit"],
       required_inputs=["output_id"], operator_authorization_policy="archive",
       write_risk="archive_move",
       additional_approval_points=["archive commit requires the server-minted approval from the plan"],
       required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["deleting the file"],
       failure_recovery="On stale surface, fail closed; re-plan the archive."),
]

WORKFLOW_IDS: frozenset[str] = frozenset(w["workflow_id"] for w in WORKFLOWS)


def workflow_record(workflow_id: str) -> dict[str, Any] | None:
    return next((w for w in WORKFLOWS if w["workflow_id"] == workflow_id), None)


def workflows_for_family(family_id: str) -> list[dict[str, Any]]:
    return [w for w in WORKFLOWS if w["family_id"] == family_id]
