"""Prompt Preflight — WORKFLOW recipes (durable routing source, seeded as static data).

Each workflow is an ordered tool recipe for a common connected-client intent, with the authorization,
retrieval-budget, provenance, and fallback fields the route engine needs. Generation workflows reference the
real N8C-24 ``pa_output_*`` tools; canonical promotion references the N8C-23 ``pa_artifact_*`` tools. Nothing
here executes — the preflight only *recommends* a recipe. Organization-neutral.
"""

from __future__ import annotations

from typing import Any

# write_risk vocabulary: none / staged_write / canonical_write / archive_move.
# action_class vocabulary (authorization): read / staged_write / canonical_promotion / archive.


def _w(**kw: Any) -> dict[str, Any]:
    base: dict[str, Any] = {
        "workflow_id": "", "family_id": "", "trigger_phrases": [], "intent_classes": [],
        "when_to_use": "", "when_not_to_use": "", "tool_sequence": [], "required_inputs": [],
        "optional_inputs": [], "operator_authorization_policy": "read", "additional_approval_points": [],
        "write_risk": "none", "default_retrieval_layer": "route_only", "max_default_candidates": 10,
        "max_default_chars": 4000, "expected_outputs": [], "required_provenance": [], "must_not_use": [],
        "fallback_rules": [], "failure_recovery": "",
        # Client vault operating-manifest projection (default off — routing-only unless published).
        "publish_to_client_manifest": False,
        "client_capability_category": "",  # session_capture|source_search|source_map|generation|decision|manifest|vault_read|preference|open_loop|staging|promotion|surface_audit|mixed_retrieval
    }
    base.update(kw)
    return base


WORKFLOWS: list[dict[str, Any]] = [
    # ---- status / discovery / routing ----
    _w(workflow_id="status_check", family_id="status_health",
       trigger_phrases=["status", "is the server up", "health", "capability mode", "what mode"],
       intent_classes=["status"], when_to_use="Operator asks whether the server/tools/queues are healthy.",
       when_not_to_use="Any content retrieval or write.", tool_sequence=["hb_mcp_status"],
       expected_outputs=["capability + gate + queue status"],
       must_not_use=["treating status as source-of-truth content"]),
    _w(workflow_id="read_only_surface_audit", family_id="status_health",
       publish_to_client_manifest=True, client_capability_category="surface_audit",
       trigger_phrases=["repo-truth audit", "repository audit", "read-only audit", "read only audit",
                        "repo truth audit", "read-only repo", "surface audit"],
       intent_classes=["status", "retrieval"],
       when_to_use="Read-only audit of server/tool surface and catalog; no mutation.",
       when_not_to_use="Content search or any write/stage/promote.",
       tool_sequence=["hb_mcp_status", "pa_tool_surface_freshness_check", "hb_assistant_catalog"],
       default_retrieval_layer="route_only",
       source_of_truth="server status + tool surface (not content)",
       expected_outputs=["status + freshness + catalog summary"],
       must_not_use=["write", "stage", "promote", "index rebuild", "deploy"]),
    _w(workflow_id="tool_help_lookup", family_id="tool_catalog_help_query",
       trigger_phrases=["what tools", "which tool", "how do I use", "what can you do"],
       intent_classes=["discovery"], when_to_use="Operator asks which tool to use / how to call it.",
       when_not_to_use="You already know the tool.",
       tool_sequence=["hb_assistant_catalog", "hb_assistant_tool_help"],
       expected_outputs=["tool catalog + per-tool help"]),
    _w(workflow_id="context_preflight", family_id="prompt_routing",
       trigger_phrases=["what should I do with", "route this", "how should I handle"],
       intent_classes=["routing"], when_to_use="Decide intent → family → workflow → tools before acting.",
       when_not_to_use="You already have a confident single-tool route.",
       tool_sequence=["pa_prompt_route"], expected_outputs=["route plan (read-only)"],
       must_not_use=["staging/writing/promoting/committing anything from the preflight"]),
    _w(workflow_id="prompt_route", family_id="prompt_routing",
       trigger_phrases=["explain the route", "why that tool"], intent_classes=["routing"],
       when_to_use="Explain a route decision.", when_not_to_use="Executing an action.",
       tool_sequence=["pa_prompt_route_explain"], expected_outputs=["route rationale"]),
    _w(workflow_id="manifest_lookup", family_id="client_tool_manifest",
       trigger_phrases=["tool manifest", "operating manifest"], intent_classes=["discovery"],
       when_to_use="Read the versioned tool operating manifest.", when_not_to_use="Routing a task.",
       tool_sequence=["pa_tool_manifest_get"], expected_outputs=["manifest record"]),
    _w(workflow_id="manifest_freshness_check", family_id="client_tool_manifest",
       publish_to_client_manifest=True, client_capability_category="manifest",
       trigger_phrases=["is the manifest current", "manifest freshness"], intent_classes=["discovery"],
       when_to_use="Check whether the manifest drifted from the live surface.", when_not_to_use="",
       tool_sequence=["pa_tool_manifest_freshness_check", "pa_tool_surface_freshness_check"],
       expected_outputs=["freshness/staleness state"]),
    _w(workflow_id="manifest_review_plan", family_id="client_tool_manifest",
       publish_to_client_manifest=True, client_capability_category="manifest",
       trigger_phrases=["review the manifest", "manifest review plan", "should I refresh the manifest",
                        "manifest review", "review manifest drift"],
       intent_classes=["discovery"],
       when_to_use="Advisory plan for whether/when to stage a manifest refresh.", when_not_to_use="",
       tool_sequence=["pa_tool_manifest_review_plan"],
       default_retrieval_layer="route_only",
       expected_outputs=["review_required + staleness guidance"],
       must_not_use=["auto-promoting a manifest refresh without operator approval"]),
    # ---- read / retrieval ----
    _w(workflow_id="source_file_search", family_id="assistant_source_connector",
       publish_to_client_manifest=True, client_capability_category="source_search",
       trigger_phrases=["which files are relevant", "files are relevant", "find the source",
                        "find the file", "find the project file",
                        "find a file", "find a source file", "search my work files",
                        "search work files", "work files", "source file", "source files",
                        "search nas", "search the nas", "source folder", "source folders",
                        "find documents in the source", "look for the file", "look for",
                        "look through", "look through the files", "search for", "search",
                        "source_file_lookup", "source_file_search", "project file",
                        "indexed nas files", "search indexed", "look in the nas",
                        "find files on the nas", "search original files", "find the original",
                        "original pdf", "search indexed files", "find documents on the nas",
                        "files on the nas", "find documents stored"],
       intent_classes=["retrieval", "discovery"],
       when_to_use="Locate an indexed NAS source file by name/topic before reading it.",
       when_not_to_use="Vault-only note search; you already have the exact card/source id.",
       tool_sequence=["assistant_source_file_search", "assistant_source_file_metadata"],
       required_inputs=["query"], default_retrieval_layer="metadata_discovery",
       expected_outputs=["candidate source list (bounded)"], required_provenance=["source_id"],
       source_of_truth="indexed NAS source files",
       fallback_rules=["if no semantic hit, fall back to hb_root_search (legacy, low-level)"],
       must_not_use=["reading full file bodies before candidate triage",
                     "using bare 'document' as the only trigger"]),
    _w(workflow_id="vault_note_search", family_id="assistant_navigation",
       publish_to_client_manifest=True, client_capability_category="vault_read",
       trigger_phrases=["search the vault", "vault for", "obsidian notes", "meeting notes",
                        "find my project notes", "project notes", "search vault",
                        "vault notes", "notes in the vault", "obsidian vault",
                        "find notes in obsidian", "search obsidian for", "find notes in the vault",
                        "obsidian vault notes", "notes in obsidian"],
       intent_classes=["retrieval", "discovery"],
       when_to_use="Search Obsidian vault notes / cards (not raw NAS file index).",
       when_not_to_use="Indexed NAS work-file search; canonical decision records.",
       tool_sequence=["assistant_search_sources", "assistant_search_cards", "assistant_get_vault_note"],
       required_inputs=["query"], default_retrieval_layer="metadata_discovery",
       expected_outputs=["vault/card candidates (bounded)"],
       source_of_truth="Obsidian vault notes and generated cards",
       must_not_use=["treating vault notes as NAS source files"]),
    _w(workflow_id="mixed_private_retrieval", family_id="assistant_navigation",
       publish_to_client_manifest=True, client_capability_category="mixed_retrieval",
       trigger_phrases=["files and notes", "files and vault", "files and obsidian",
                        "find files and notes", "search files and notes",
                        "source files and notes", "nas files and notes",
                        "indexed files and notes", "notes and files",
                        "work files and notes", "project files and notes"],
       intent_classes=["retrieval", "discovery"],
       when_to_use="Explicit dual-intent: search indexed NAS source files AND vault notes together.",
       when_not_to_use="Single-surface search (NAS-only or vault-only); canonical memory lookups.",
       tool_sequence=["assistant_source_file_search", "assistant_search_sources"],
       required_inputs=["query"], default_retrieval_layer="metadata_discovery",
       expected_outputs=["bounded NAS file candidates + bounded vault note candidates"],
       source_of_truth="indexed NAS source files + Obsidian vault notes",
       must_not_use=["silently choosing only vault or only NAS when both were requested",
                     "treating mixed retrieval as ambiguous notes without clarification"]),
    _w(workflow_id="source_query_plan", family_id="assistant_source_connector",
       trigger_phrases=["plan source search", "how should I search the nas", "source query plan",
                        "where should i look for"],
       intent_classes=["routing", "retrieval"],
       when_to_use="Classify a NAS source prompt before searching or mapping.",
       when_not_to_use="Vault-only questions.",
       tool_sequence=["assistant_source_query_plan"],
       required_inputs=["prompt"],
       default_retrieval_layer="route_only",
       expected_outputs=["intent + recommended tool sequence"], required_provenance=[]),
    _w(workflow_id="source_index_health", family_id="assistant_source_connector",
       publish_to_client_manifest=True, client_capability_category="source_map",
       trigger_phrases=["source index health", "is my source index fresh", "index fresh enough",
                        "source freshness", "can i trust the source index"],
       intent_classes=["status"],
       when_to_use="Check whether NAS source index/map layers are trustworthy.",
       when_not_to_use="File content questions.",
       tool_sequence=["assistant_source_index_health", "assistant_source_status"],
       default_retrieval_layer="route_only"),
    _w(workflow_id="source_project_map", family_id="assistant_source_connector",
       publish_to_client_manifest=True, client_capability_category="source_map",
       trigger_phrases=["map the project", "map project", "project folder map",
                        "project map", "where is project", "folders for project",
                        "map project folder", "map the project folder", "project folder",
                        "map folder"],
       intent_classes=["retrieval", "discovery"],
       when_to_use="Locate project folders across NAS roots by project number or name.",
       when_not_to_use="Generic vault search.",
       tool_sequence=["assistant_source_query_plan", "assistant_source_project_map",
                      "assistant_source_folder_map", "assistant_source_folder_summary"],
       required_inputs=["prompt"],
       default_retrieval_layer="metadata_discovery",
       must_not_use=["using file search alone for folder mapping"]),
    _w(workflow_id="source_folder_map", family_id="assistant_source_connector",
       trigger_phrases=["folder structure", "map the folder", "show me the folder", "folder tree",
                        "structure under", "list folders under", "children of the folder",
                        "what is in the", "what's in the"],
       intent_classes=["retrieval", "discovery"],
       when_to_use="Browse NAS folder hierarchy without brute-force file search.",
       when_not_to_use="Full-text content search.",
       tool_sequence=["assistant_source_root_map", "assistant_source_folder_map",
                      "assistant_source_folder_summary"],
       default_retrieval_layer="metadata_discovery"),
    _w(workflow_id="source_root_map", family_id="assistant_source_connector",
       trigger_phrases=["source root", "map the root", "nas roots", "work source root",
                        "2023 projects source", "list configured source roots",
                        "configured source roots", "source roots", "source map"],
       intent_classes=["discovery"],
       when_to_use="List/rank NAS source roots for navigation.",
       when_not_to_use="File content search.",
       tool_sequence=["assistant_source_roots_list", "assistant_source_root_map"],
       default_retrieval_layer="metadata_discovery",
       source_of_truth="indexed source configuration"),
    _w(workflow_id="source_unsupported_read", family_id="assistant_source_connector",
       trigger_phrases=["read this xer", "xer file", "unsupported file", "primavera", ".xer"],
       intent_classes=["retrieval"],
       when_to_use="Discover unsupported schedule/binary files honestly (metadata only).",
       when_not_to_use="Pretending content was extracted.",
       tool_sequence=["assistant_source_file_search", "assistant_source_file_metadata",
                      "assistant_source_file_read"],
       required_inputs=["query"],
       default_retrieval_layer="metadata_discovery",
       must_not_use=["inventing xer content"]),
    _w(workflow_id="source_file_metadata_review", family_id="assistant_navigation",
       trigger_phrases=["metadata for", "details about the source"], intent_classes=["retrieval"],
       when_to_use="Inspect source/card metadata before a bounded read.", when_not_to_use="",
       tool_sequence=["assistant_source_file_metadata"], default_retrieval_layer="metadata_discovery",
       required_provenance=["source_id"]),
    _w(workflow_id="source_file_bounded_read", family_id="assistant_navigation",
       trigger_phrases=["read the source", "open and read", "read an excerpt", "read the excerpt",
                        "excerpt", "read the file", "read this file", "read the document"],
       intent_classes=["retrieval"],
       when_to_use="Bounded read once the exact source id/filename is known.",
       when_not_to_use="Broad/ambiguous ask — triage candidates first.",
       tool_sequence=["assistant_source_file_read"], required_inputs=["source_id"],
       default_retrieval_layer="bounded_read", max_default_chars=4000, required_provenance=["source_id"]),
    _w(workflow_id="context_pack_retrieval", family_id="assistant_context_packs",
       trigger_phrases=["assemble context", "context pack", "what do we know", "background on"],
       intent_classes=["retrieval"], when_to_use="Assemble a durable context pack for a topic.",
       when_not_to_use="Single exact-id lookup.",
       tool_sequence=["assistant_get_context_pack"], default_retrieval_layer="candidate_triage",
       required_provenance=["source_id"]),
    _w(workflow_id="canonical_decision_retrieval", family_id="assistant_decision_memory",
       publish_to_client_manifest=True, client_capability_category="decision",
       trigger_phrases=["what did we decide", "the decision on", "was it decided",
                        "get decision", "retrieve the decision", "retrieve the canonical decision",
                        "show me decision", "show me the decision"],
       intent_classes=["retrieval"], when_to_use="Retrieve a canonical decision record.",
       when_not_to_use="Free-text source search.",
       # Discovery-first: list/bounded discovery before get-by-id.
       tool_sequence=["assistant_list_decisions", "assistant_get_decision"],
       required_inputs=["decision_id"],  # for getter; list step has no topic query arg
       required_provenance=["source_id", "decision_id"],
       fallback_rules=["if no canonical decision, fall back to source search — clearly labeled non-canonical"]),
    _w(workflow_id="canonical_preference_retrieval", family_id="assistant_decision_memory",
       publish_to_client_manifest=True, client_capability_category="preference",
       trigger_phrases=["standing preference", "how do we usually", "the preference for",
                        "what preferences", "preferences do i have", "preferences for",
                        "retrieve the preference", "get preference"],
       intent_classes=["retrieval"], when_to_use="Retrieve a standing preference.", when_not_to_use="",
       tool_sequence=["assistant_list_preferences", "assistant_get_preference"],
       required_inputs=["preference_id"],
       required_provenance=["source_id"]),
    _w(workflow_id="canonical_open_loop_retrieval", family_id="assistant_decision_memory",
       publish_to_client_manifest=True, client_capability_category="open_loop",
       trigger_phrases=["open loops", "what is pending", "unresolved", "what open loops remain",
                        "open loops remain", "retrieve the open loop", "get open loop"],
       intent_classes=["retrieval"],
       when_to_use="List open loops / unresolved threads.", when_not_to_use="",
       tool_sequence=["assistant_list_open_loops", "assistant_get_open_loop"],
       required_inputs=["open_loop_id"],
       required_provenance=["source_id"]),
    _w(workflow_id="quality_findings_review", family_id="assistant_quality",
       trigger_phrases=["quality findings", "what needs review", "review queue"],
       intent_classes=["retrieval"], when_to_use="Review advisory quality findings / review queue.",
       when_not_to_use="Writing a disposition.", tool_sequence=["assistant_get_review_summary"],
       must_not_use=["repairing or rebuilding from a client"]),
    _w(workflow_id="feedback_review", family_id="assistant_feedback",
       trigger_phrases=["feedback", "recommendations"], intent_classes=["retrieval"],
       when_to_use="Read feedback-loop recommendations (advisory).", when_not_to_use="",
       tool_sequence=["assistant_get_feedback"]),
    _w(workflow_id="action_stage_review", family_id="assistant_action_stages",
       trigger_phrases=["staged actions", "action stage"], intent_classes=["retrieval"],
       when_to_use="Inspect staged actions (staging is not execution).",
       when_not_to_use="Executing/sending anything.", tool_sequence=["assistant_get_action_stage"],
       must_not_use=["executing staged actions; no send/email/calendar"]),
    # ---- artifact workspace (session capture → staged canonical) ----
    _w(workflow_id="document_session", family_id="artifact_workspace",
       publish_to_client_manifest=True, client_capability_category="session_capture",
       trigger_phrases=["document this session", "capture this", "remember this", "save to memory",
                        "write this down", "log our decisions",
                        # artifact-authoring phrasings (were classified "unknown" before)
                        "create a decision artifact", "create an artifact", "create a decision",
                        "document this as a decision", "document this as decisions",
                        "capture this as a preference", "save this as an open loop",
                        "capture our decisions", "record our decisions"],
       intent_classes=["capture", "staged_write"],
       when_to_use="Capture a session's decisions/preferences/open-loops as staged artifact proposals.",
       when_not_to_use="Generating a work-product file (use client_output_workspace).",
       tool_sequence=["pa_session_capture_stage", "pa_artifact_proposal_stage",
                      "pa_artifact_proposal_review"],
       required_inputs=["session_summary"], operator_authorization_policy="staged_write",
       write_risk="staged_write",
       additional_approval_points=["canonical promotion needs a separate server-minted approval"],
       expected_outputs=["staged artifact proposals (nothing written to the vault yet)"],
       required_provenance=["session_capture_id"],
       must_not_use=["writing the vault directly", "promoting without explicit approval"],
       fallback_rules=["never fall back to hb_output_write_file or a raw vault write"]),
    _w(workflow_id="stage_artifact_proposals", family_id="artifact_workspace",
       publish_to_client_manifest=True, client_capability_category="staging",
       trigger_phrases=["stage proposals", "prepare memory records", "stage this for review",
                        "stage for review", "stage this", "stage it for review",
                        "put this up for review", "submit for review", "queue for review",
                        "create a proposal", "create proposal", "make a proposal"],
       intent_classes=["staged_write"],
       when_to_use="Stage artifact proposals from an existing capture.", when_not_to_use="",
       tool_sequence=["pa_artifact_proposal_stage"], operator_authorization_policy="staged_write",
       write_risk="staged_write", required_inputs=["session_id", "candidate_artifacts"],
       required_provenance=["session_capture_id"]),
    _w(workflow_id="review_artifact_proposals", family_id="artifact_workspace",
       trigger_phrases=["review proposals", "show staged memory"], intent_classes=["retrieval"],
       when_to_use="Review staged proposals before promotion.", when_not_to_use="",
       tool_sequence=["pa_artifact_proposal_list", "pa_artifact_proposal_get",
                      "pa_artifact_proposal_compare"]),
    _w(workflow_id="revise_artifact_proposal", family_id="artifact_workspace",
       trigger_phrases=["revise the proposal", "edit the staged memory"], intent_classes=["staged_write"],
       when_to_use="Revise a staged proposal before promotion.", when_not_to_use="",
       tool_sequence=["pa_artifact_proposal_revise"], operator_authorization_policy="staged_write",
       write_risk="staged_write"),
    # ---- canonical promotion ----
    _w(workflow_id="plan_canonical_promotion", family_id="canonical_promotion",
       publish_to_client_manifest=True, client_capability_category="promotion",
       trigger_phrases=["plan promotion", "prepare to promote", "what would happen if",
                        "what happens if i promote", "what would happen if i promoted"],
       intent_classes=["retrieval"],
       when_to_use="Plan a canonical promotion (still no write).", when_not_to_use="",
       tool_sequence=["pa_artifact_proposal_plan_promotion"],
       must_not_use=["applying promotion without explicit server-minted approval"]),
    _w(workflow_id="validate_canonical_promotion", family_id="canonical_promotion",
       trigger_phrases=["validate promotion"], intent_classes=["retrieval"],
       when_to_use="Validate a planned promotion + mint approval.", when_not_to_use="",
       tool_sequence=["pa_artifact_promotion_validate"],
       expected_outputs=["validation result + server-minted approval id"]),
    _w(workflow_id="apply_canonical_promotion", family_id="canonical_promotion",
       trigger_phrases=["promote", "make canonical", "finalize the decision record", "apply promotion"],
       intent_classes=["canonical_promotion"],
       when_to_use="Apply an approved canonical promotion to Obsidian cards.",
       when_not_to_use="Ordinary file export (use client_output_workspace).",
       tool_sequence=["pa_artifact_promotion_apply"],
       required_inputs=["promotion_bundle_id", "operator_approval_id"],
       operator_authorization_policy="canonical_promotion",
       write_risk="canonical_write",
       additional_approval_points=["requires server-minted approval id + prior validation"],
       required_provenance=["proposal_id", "operator_approval_id"],
       must_not_use=["inventing an approval id", "a broad vault write"],
       fallback_rules=["never fall back to a raw vault write on failure"],
       failure_recovery="On stale tool surface or approval mismatch, fail closed and re-validate."),
    _w(workflow_id="inspect_promotion_receipt", family_id="canonical_promotion",
       trigger_phrases=["was it promoted", "inspect promotion receipt", "explain promotion receipt",
                        "review promotion receipt", "retrieve promotion receipt",
                        "search promotion receipt"],
       intent_classes=["retrieval"],
       when_to_use="Inspect a promotion receipt/manifest.", when_not_to_use="Bare receipt noun mentions",
       tool_sequence=["pa_artifact_promotion_receipt_get", "pa_artifact_manifest_get"]),
    # ---- generated file output workspace (N8C-24) ----
    _w(workflow_id="generate_docx_output", family_id="client_output_workspace",
       publish_to_client_manifest=True, client_capability_category="generation",
       trigger_phrases=["generate a word doc", "make a word document", "save this as docx",
                        "write a report and save it"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a DOCX work-product file and save it to the outputs root.",
       when_not_to_use="Canonical memory or an Obsidian note.",
       tool_sequence=["pa_output_stage", "pa_output_commit"],
       required_inputs=["title", "content", "content_mode"], operator_authorization_policy="staged_write",
       write_risk="staged_write",
       additional_approval_points=["commit requires the server-minted approval id from staging"],
       expected_outputs=["committed DOCX under the outputs root + receipt + manifest entry"],
       required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["writing to the Obsidian vault", "canonical promotion",
                     "the legacy hb_output_write_file scratch writer"],
       fallback_rules=["never fall back to hb_output_write_file"],
       failure_recovery="On hash drift/stale surface, fail closed; re-stage a new version."),
    _w(workflow_id="generate_xlsx_output", family_id="client_output_workspace",
       trigger_phrases=["make a spreadsheet", "excel file", "save as xlsx", "export to excel"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce an XLSX from CSV/tabular content.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["the legacy hb_output_write_file scratch writer"]),
    _w(workflow_id="generate_pdf_output", family_id="client_output_workspace",
       trigger_phrases=["make a pdf", "save as pdf", "generate a pdf report"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a PDF (reportlab) from markdown/text/html.",
       when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"],
       expected_outputs=["committed PDF (basic Platypus layout) + receipt"]),
    _w(workflow_id="generate_pptx_output", family_id="client_output_workspace",
       trigger_phrases=["make a powerpoint", "slide deck", "save as pptx"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a PPTX from markdown/json.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"]),
    _w(workflow_id="generate_markdown_output", family_id="client_output_workspace",
       trigger_phrases=["save as markdown", "make a markdown file", "export notes as md",
                       "create a markdown output", "markdown output", "temporary markdown",
                       "create a temporary markdown", "generated outputs workspace"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a standalone markdown FILE (not a vault note).",
       when_not_to_use="Canonical memory / an Obsidian note — those are different surfaces.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["confusing a generated .md file with an Obsidian vault note"]),
    _w(workflow_id="generate_csv_output", family_id="client_output_workspace",
       trigger_phrases=["save as csv", "export to csv"], intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a CSV file.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"]),
    _w(workflow_id="generate_json_output", family_id="client_output_workspace",
       trigger_phrases=["save as json", "export json"], intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce a JSON file.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"]),
    _w(workflow_id="generate_html_output", family_id="client_output_workspace",
       trigger_phrases=["save as html", "export html"], intent_classes=["generate_file", "staged_write"],
       when_to_use="Produce an HTML file.", when_not_to_use="Canonical memory.",
       tool_sequence=["pa_output_stage", "pa_output_commit"], required_inputs=["title", "content"],
       operator_authorization_policy="staged_write", write_risk="staged_write",
       required_provenance=["output_id", "operator_approval_id"]),
    _w(workflow_id="generate_zip_package", family_id="client_output_workspace",
       trigger_phrases=["make a zip", "bundle these files", "zip package", "export as zip",
                       "temporary zip", "create a temporary zip", "zip output"],
       intent_classes=["generate_file", "staged_write"],
       when_to_use="Assemble a validated ZIP (from base64 or already-committed outputs).",
       when_not_to_use="Canonical memory; anything requiring extraction.",
       tool_sequence=["pa_output_stage", "pa_output_zip_inspect", "pa_output_commit"],
       required_inputs=["title", "content"], operator_authorization_policy="staged_write",
       write_risk="staged_write", required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["extracting a ZIP", "executable/script members", "traversal/absolute member paths"],
       fallback_rules=["a ZIP that fails validation is never written"]),
    # ---- output receipts / manifest / archive ----
    _w(workflow_id="list_generated_outputs", family_id="output_receipts_manifests",
       trigger_phrases=["list outputs", "what files did I generate", "show generated files"],
       intent_classes=["retrieval"], when_to_use="List generated outputs.", when_not_to_use="",
       tool_sequence=["pa_output_list"], default_retrieval_layer="metadata_discovery"),
    _w(workflow_id="inspect_generated_output_metadata", family_id="output_receipts_manifests",
       trigger_phrases=["details on the output", "output metadata", "where did the file go"],
       intent_classes=["retrieval"], when_to_use="Inspect one generated output's metadata.",
       when_not_to_use="", tool_sequence=["pa_output_metadata", "pa_output_read_excerpt"],
       default_retrieval_layer="metadata_discovery"),
    _w(workflow_id="retrieve_generated_output_receipt", family_id="output_receipts_manifests",
       trigger_phrases=["output receipt", "receipt for the file", "output manifest"],
       intent_classes=["retrieval"], when_to_use="Retrieve an output receipt/manifest.",
       when_not_to_use="", tool_sequence=["pa_output_receipt_get", "pa_output_manifest_get"]),
    _w(workflow_id="archive_generated_output", family_id="output_receipts_manifests",
       trigger_phrases=["archive the output", "move the file to archive",
                       "archive the temporary outputs", "cleanup generated outputs"],
       intent_classes=["archive", "staged_write"],
       when_to_use="Archive a committed output (staged plan → approved move; never delete).",
       when_not_to_use="Deleting a file (deletion is not offered).",
       tool_sequence=["pa_output_archive_plan", "pa_output_archive_commit"],
       required_inputs=["output_id"], operator_authorization_policy="archive",
       write_risk="archive_move",
       additional_approval_points=["archive commit requires the server-minted approval from the plan"],
       required_provenance=["output_id", "operator_approval_id"],
       must_not_use=["deleting the file"],
       failure_recovery="On stale surface, fail closed; re-plan the archive."),
]

WORKFLOW_IDS: frozenset[str] = frozenset(w["workflow_id"] for w in WORKFLOWS)


def workflow_record(workflow_id: str) -> dict[str, Any] | None:
    return next((w for w in WORKFLOWS if w["workflow_id"] == workflow_id), None)


def workflows_for_family(family_id: str) -> list[dict[str, Any]]:
    return [w for w in WORKFLOWS if w["family_id"] == family_id]
