#!/usr/bin/env bash
# Fast, local forecasting-domain pytest bundle.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PYTHON_BIN="${PYTHON:-}"
if [[ -z "$PYTHON_BIN" ]]; then
  if [[ -x "$ROOT/.venv/bin/python" ]]; then
    PYTHON_BIN="$ROOT/.venv/bin/python"
  elif [[ -x "/Users/bobbyfetting/hb-personal-assistant/.venv/bin/python" ]]; then
    PYTHON_BIN="/Users/bobbyfetting/hb-personal-assistant/.venv/bin/python"
  else
    PYTHON_BIN="python"
  fi
fi

export PYTHONPATH="$ROOT/src:$ROOT/subrepos/construction-financial-review/src${PYTHONPATH:+:$PYTHONPATH}"

pytest_targets=(
  "tests/test_fastapi_forecast_browser.py"
  "tests/test_fastapi_forecast_config.py"
  "tests/test_fastapi_forecast_config_edit.py"
  "tests/test_fastapi_forecast_config_promotion.py"
  "tests/test_fastapi_forecast_db_config_run.py"
  "tests/test_fastapi_forecast_db_native_persistence.py"
  "tests/test_fastapi_forecast_external.py"
  "tests/test_fastapi_forecast_generation_date_defaults.py"
  "tests/test_fastapi_forecast_generation_db_persistence.py"
  "tests/test_fastapi_forecast_generation_projects.py"
  "tests/test_fastapi_forecast_generation_requests.py"
  "tests/test_fastapi_forecast_operator_assumptions.py"
  "tests/test_fastapi_forecast_run.py"
  "tests/test_fastapi_forecast_run_readmodel.py"
  "tests/test_fastapi_forecast_runtime.py"
  "tests/test_forecast_assumptions_consume_p2.py"
  "tests/test_forecast_bootstrap.py"
  "tests/test_forecast_catalog_service.py"
  "tests/test_forecast_comprehensive_db_config_phase20.py"
  "tests/test_forecast_comprehensive_db_config_phase20_stability.py"
  "tests/test_forecast_config_catalog.py"
  "tests/test_forecast_config_edit_service.py"
  "tests/test_forecast_config_registry_phase16.py"
  "tests/test_forecast_context_generator_phase5.py::test_build_with_temp_config_writes_under_temp"
  "tests/test_forecast_context_generator_phase5.py::test_import_is_side_effect_free"
  "tests/test_forecast_context_generator_phase5.py::test_file_backed_and_db_backed_full_package_parity"
  "tests/test_forecast_context_generator_phase5.py::test_global_reset_proven_in_both_orders"
  "tests/test_forecast_context_generator_phase5.py::test_db_backed_fails_closed_when_rows_missing"
  "tests/test_forecast_context_generator_phase5.py::test_db_backed_fails_closed_without_db_path"
  "tests/test_forecast_context_generator_phase5.py::test_db_backed_refuses_live_db_path"
  "tests/test_forecast_context_generator_phase5.py::test_toggle_off_default_is_file_backed"
  "tests/test_forecast_context_runner_phase6.py"
  "tests/test_forecast_controlled_workflow_phase9.py"
  "tests/test_forecast_correctness_values_p10.py"
  "tests/test_forecast_db_certified_final_output_phase15.py"
  "tests/test_forecast_db_config_backed_generation.py"
  "tests/test_forecast_db_config_backed_generation_kinds.py"
  "tests/test_forecast_db_cutover_readiness_phase10.py"
  "tests/test_forecast_db_native_context_builder.py"
  "tests/test_forecast_db_native_contract.py"
  "tests/test_forecast_db_native_engine_adapter.py"
  "tests/test_forecast_db_native_generation_engine.py"
  "tests/test_forecast_db_native_inputs_p3.py"
  "tests/test_forecast_db_native_output_persistence.py"
  "tests/test_forecast_db_native_source_snapshot.py"
  "tests/test_forecast_db_native_summary.py"
  "tests/test_forecast_db_read_adapter_phase4.py"
  "tests/test_forecast_db_read_repositories_phase3.py"
  "tests/test_forecast_db_transition_schema_v58.py"
  "tests/test_forecast_decision_support_coverage.py"
  "tests/test_forecast_decision_support_phase2b.py"
  "tests/test_forecast_external_eval_service.py"
  "tests/test_forecast_external_metrics.py"
  "tests/test_forecast_final_runner_phase7.py"
  "tests/test_forecast_generation_date_defaults.py"
  "tests/test_forecast_generation_db_persistence.py"
  "tests/test_forecast_generation_request_repository.py"
  "tests/test_forecast_guarded_db_operator_run_phase12.py"
  "tests/test_forecast_lineage_completeness_p8.py"
  "tests/test_forecast_live_db_certification_phase13.py"
  "tests/test_forecast_live_db_config_registry_promotion_phaseE2.py"
  "tests/test_forecast_live_db_run_output_projection.py"
  "tests/test_forecast_live_db_source_domain_projection_phase14.py"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_refuses_missing_live_db"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_refuses_schema_below_v60"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_refuses_missing_config_tables"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_refuses_missing_snapshot"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_refuses_wrong_project_snapshot"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_refuses_item_count_mismatch"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_refuses_require_live_snapshot_on_temp_db"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_parity_ready_and_materialized"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_cfr_config_root_scoped_and_restored"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_file_backed_default_reader_unchanged_when_unset"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_db_backed_consumes_materialized_config"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_outputs_and_report_under_work_root"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_parity_mismatch_reports_differences"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_safety_block_no_live_write"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_no_ollama_or_llm_import_in_generator"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_cli_success_rc0"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_cli_refusal_rc3"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_cli_mismatch_rc1"
  "tests/test_forecast_model_controls_db_config_phase17.py::test_existing_commands_still_route"
  "tests/test_forecast_model_engines_readiness_phase_i_pr1.py"
  "tests/test_forecast_model_registry_p6.py"
  "tests/test_forecast_monthly_db_config_phase18.py"
  "tests/test_forecast_monthly_db_config_phase18a_stability.py"
  "tests/test_forecast_monthly_matrix.py"
  "tests/test_forecast_operator_assumptions_service.py"
  "tests/test_forecast_output_coverage.py"
  "tests/test_forecast_output_narratives_p8.py"
  "tests/test_forecast_output_overrides_p2b.py"
  "tests/test_forecast_output_projection_phase2a.py"
  "tests/test_forecast_p5_maturity_availability.py"
  "tests/test_forecast_package_resolution_phase8.py"
  "tests/test_forecast_probability_db_config_phase19.py"
  "tests/test_forecast_probability_db_config_phase19_stability.py"
  "tests/test_forecast_projection_phase2.py"
  "tests/test_forecast_run_service.py"
  "tests/test_forecast_runtime_config.py"
  "tests/test_forecast_source_qa_p8.py"
  "tests/test_forecast_temp_db_readiness_rehearsal_phase11.py"
  "tests/test_forecasting_db_evidence_package.py"
  "tests/test_forecasting_evidence_script_integration.py"
  "tests/test_forecasting_external_fixture.py"
  "tests/test_forecasting_field_classifiers.py"
  "tests/test_forecasting_gates.py"
  "tests/test_forecasting_project_eligibility.py"
  "tests/test_forecasting_projection_parity_keys.py"
  "tests/test_forecasting_readiness.py"
  "tests/test_forecasting_runtime_normalization.py"
  "tests/test_forecasting_semantic_catalog.py"
  "tests/test_migrator_v61_external_forecasts.py"
  "tests/test_migrator_v63_forecast_outputs.py"
  "tests/test_migrator_v66_forecast_decision_support.py"
  "tests/test_migrator_v72_forecast_model_registry.py"
  "tests/test_migrator_v73_forecast_generation_requests.py"
  "tests/test_phase_08c_financial_completeness.py::test_currency_explicit_and_missing_and_inconsistent_and_default_policy"
  "tests/test_phase_08c_financial_completeness.py::test_wbs_cost_line_source_missing_routes_to_review"
  "tests/test_phase_08c_financial_completeness.py::test_default_currency_blocked_when_policy_condition_missing"
  "tests/test_phase_08c_financial_completeness.py::test_financial_source_coverage_matrix_maps_classifies_counts_no_raw"
  "tests/test_phase_08c_financial_completeness.py::test_financial_exposure_read_models_mart_preview"
  "tests/test_phase_08c_financial_completeness.py::test_financial_fact_readiness_agent"
  "tests/test_phase_08c_gates.py"
  "tests/test_procore_budget_normalizers.py"
  "tests/test_procore_budget_projection.py"
  "tests/test_procore_commitment_normalizers.py"
  "tests/test_procore_commitment_projection.py"
  "tests/test_procore_cost_exposure.py"
  "tests/test_procore_financial_normalizers.py"
  "tests/test_procore_financial_projection.py"
  "tests/test_procore_invoice_projection.py"
  "tests/test_procore_normalizers_financial_amounts.py"
  "tests/test_procore_owner_contract_normalizers.py"
  "tests/test_procore_owner_projection.py"
  "tests/test_procore_subcontractor_invoice_normalizers.py"
)

echo "=== Fast forecasting test bundle ==="
"$PYTHON_BIN" -m pytest -m "not integration and not manual and not live" "${pytest_targets[@]}" "$@"
