"""Phase 04A canonical endpoint adapter registry.

The 14 IDs listed in ``12_Endpoint_Command_Matrix.md`` are the canonical
command-surface scheme. Each row carries everything the live sync orchestrator
needs to honor the contract (path template, pagination shape, parent/child
routing, review-required hint, SQLite target, and live-verified gate).

Existing pre-04A keys (``list-rfis``, ``list-submittals``, ...) remain valid
input via the ``legacy_endpoint_alias`` field so backward-compatible callers
keep working without a rename pass.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple


@dataclass(frozen=True)
class EndpointAdapter:
    """One row of the canonical endpoint matrix."""

    endpoint_id: str
    family: str
    legacy_endpoint_alias: Optional[str]
    path_template: str
    parent_path_template: Optional[str]  # for child endpoints, the parent list path
    required_path_params: Tuple[str, ...]  # path parameters supplied at call time
    pagination: str  # "page+per_page" | "none"
    record_id_field: str
    parent_record_id_field: Optional[str]
    review_required_default: bool
    sensitivity: str  # "low" | "medium" | "high" | "critical"
    sqlite_target: str  # canonical table name (procore_live_records)
    live_verified: bool
    verification_reason: str
    # Top-level response envelope shape: "array" (bare list), "object" (single
    # object / wrapped non-data list), or "object.data[]" (Procore v2 data[]
    # cursor wrapper). Defaulted so the pre-05 rows are unchanged; the Phase 05
    # financial rows set it explicitly per the endpoint matrix.
    response_envelope: str = "array"


# Canonical endpoint registry. The Phase 04A/04B operational rows are
# live_verified=True (docs/smoke verified); the Phase 05 financial rows
# appended at the end are live_verified=False — command-visible but
# fail-closed at orchestration time until per-endpoint smoke evidence.
_ENDPOINTS: Tuple[EndpointAdapter, ...] = (
    EndpointAdapter(
        endpoint_id="projects",
        family="foundation",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects",
        parent_path_template=None,
        required_path_params=(),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="low",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:7703b766",
    ),
    EndpointAdapter(
        endpoint_id="rfis",
        family="rfis",
        legacy_endpoint_alias="list-rfis",
        path_template="/rest/v1.0/projects/{project_id}/rfis",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:09113b6d",
    ),
    EndpointAdapter(
        endpoint_id="rfi-responses",
        family="rfis",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/rfis/{rfi_id}/replies",
        parent_path_template="/rest/v1.0/projects/{project_id}/rfis",
        required_path_params=("project_id", "rfi_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="rfi_id",
        review_required_default=True,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_apply_n_plus_1_passed_via_rfis_parent_2026-05-28",
    ),
    EndpointAdapter(
        endpoint_id="submittals",
        family="submittals",
        legacy_endpoint_alias="list-submittals",
        path_template="/rest/v1.0/projects/{project_id}/submittals",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:d9506311",
    ),
    EndpointAdapter(
        endpoint_id="submittal-responses",
        family="submittals",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/submittals/{submittal_id}/responses",
        parent_path_template="/rest/v1.0/projects/{project_id}/submittals",
        required_path_params=("project_id", "submittal_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="submittal_id",
        review_required_default=True,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="populated_via_submittals_inline_extraction_2026-05-28",
    ),
    EndpointAdapter(
        endpoint_id="submittal-packages",
        family="submittals",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/submittal_packages",
        parent_path_template="/rest/v1.0/projects/{project_id}/submittals",
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:7b9077ee",
    ),
    EndpointAdapter(
        endpoint_id="observations",
        family="observations",
        legacy_endpoint_alias="list-observations",
        path_template="/rest/v1.0/projects/{project_id}/observations/items",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:2d0a091f",
    ),
    EndpointAdapter(
        endpoint_id="meetings",
        family="meetings",
        legacy_endpoint_alias="list-meetings",
        path_template="/rest/v1.1/projects/{project_id}/meetings",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:452d9421",
    ),
    EndpointAdapter(
        endpoint_id="meeting-detail",
        family="meetings",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.1/projects/{project_id}/meetings/{id}",
        parent_path_template="/rest/v1.1/projects/{project_id}/meetings",
        required_path_params=("project_id", "id"),
        pagination="none",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:7eaf5ae6_list_plus_n_detail_with_pii_hashed_summaries",
    ),
    EndpointAdapter(
        endpoint_id="meeting-topics",
        family="meetings",
        legacy_endpoint_alias="list-meeting-topics",
        path_template="/rest/v1.1/projects/{project_id}/meeting_topics",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:a0499320_max_per_page_10_server_500_at_100",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-weather",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.1/projects/{project_id}/daily_logs/weather_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="low",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:26762b35_v1.1_daily_logs_path",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-manpower",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/manpower_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="low",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:22391cff_contact_pii_hashed",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-notes",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/notes_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:f5e0e409_comment_hashed",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-deliveries",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/delivery_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:ec249d59",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-delays-review-routed",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/delay_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="critical",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:c31a788f_safety_routed",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-inspections",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/inspection_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:6ea9b013",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-dcrs",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/daily_construction_report_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:95f5a809",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-accident-review-routed",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/accident_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="critical",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:b9538451_safety_routed",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-dumpster",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/dumpster_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="low",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:7a99ff77",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-safety-violation-review-routed",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/safety_violation_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="critical",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:1cc4bd61_safety_routed",
    ),
    EndpointAdapter(
        endpoint_id="daily-log-visitor",
        family="daily_logs",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/visitor_logs",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-29:e968273f_subject_pii_hashed",
    ),
    EndpointAdapter(
        endpoint_id="punch-items",
        family="punch_items",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.1/punch_items",
        parent_path_template=None,
        # project_id is required but passed as a query param by the orchestrator
        # (existing branch: params={"project_id": ...} if "{project_id}" not in path).
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:0277eee6_pii_hashed_free_text_summaries",
    ),
    EndpointAdapter(
        endpoint_id="schedules",
        family="schedules",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/schedules",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="schedule_id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:980e7fb0_v2_data_envelope",
    ),
    EndpointAdapter(
        endpoint_id="activities",
        family="schedules",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/schedules/{schedule_id}/activities",
        parent_path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/schedules",
        required_path_params=("project_id", "schedule_id"),
        pagination="page+per_page",
        record_id_field="activity_id",
        parent_record_id_field="schedule_id",
        review_required_default=False,
        sensitivity="medium",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="live_smoke_passed_2026-05-28:6956f007_list_plus_n_per_schedule_notes_hashed",
    ),
    EndpointAdapter(
        endpoint_id="inspections",
        family="inspections",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/checklist/lists",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="operator_supplied_schema_2026-05-29",
    ),
    EndpointAdapter(
        endpoint_id="inspection-sections",
        family="inspections",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/checklist/list_sections",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=False,
        sensitivity="low",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="operator_supplied_list_endpoint_2026-05-29",
    ),
    EndpointAdapter(
        endpoint_id="inspection-items",
        family="inspections",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.1/projects/{project_id}/checklist/list_items",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="list_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="operator_supplied_list_endpoint_2026-05-29:v1.1",
    ),
    # ------------------------------------------------------------------
    # Phase 05 financial / contract-control registry shells (32 rows).
    # All start live_verified=False — command-visible (catalog/listing) but
    # fail-closed at orchestration time (no transport) until per-endpoint
    # smoke evidence promotes them. No normalizers are registered yet
    # (Prompts 03-09 own the real financial normalizers); resolve_normalizer()
    # returns None, so even a hypothetical promotion would fail closed
    # (normalizer_missing). Envelope / pagination / sqlite_target are
    # provisional metadata sourced from the attached endpoint matrix and are
    # re-confirmed at live promotion. sqlite_target stays procore_live_records
    # as a placeholder; the V8 financial projection target lands in Prompt 02.
    # All financial rows are sensitivity="high" per the Phase 05 posture.
    # ---- Owner contracts (prime contracts + change orders) ----
    EndpointAdapter(
        endpoint_id="prime-contracts",
        family="owner_contracts",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/prime_contracts",
        parent_path_template=None,
        required_path_params=(),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="prime-contract-line-items",
        family="owner_contracts",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/prime_contracts/{prime_contract_id}/line_items",
        parent_path_template="/rest/v1.0/prime_contracts",
        required_path_params=("company_id", "project_id", "prime_contract_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="prime_contract_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object.data[]",
    ),
    EndpointAdapter(
        endpoint_id="prime-contract-attachments",
        family="owner_contracts",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/prime_contracts/{prime_contract_id}/attachments",
        parent_path_template="/rest/v1.0/prime_contracts",
        required_path_params=("company_id", "project_id", "prime_contract_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="prime_contract_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object.data[]",
    ),
    EndpointAdapter(
        endpoint_id="prime-change-orders",
        family="owner_contracts",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/prime_change_orders",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object",
    ),
    EndpointAdapter(
        endpoint_id="prime-change-order-line-items",
        family="owner_contracts",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/prime_change_orders/{prime_change_order_id}/line_items",
        parent_path_template="/rest/v1.0/projects/{project_id}/prime_change_orders",
        required_path_params=("company_id", "project_id", "prime_change_order_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="prime_change_order_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object.data[]",
    ),
    # ---- Owner billing (payment applications) ----
    EndpointAdapter(
        endpoint_id="payment-applications",
        family="owner_billing",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/prime_contracts/{prime_contract_id}/payment_applications",
        parent_path_template="/rest/v1.0/prime_contracts",
        required_path_params=("prime_contract_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="prime_contract_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    # ---- Commitments (subcontracts + change orders) ----
    EndpointAdapter(
        endpoint_id="commitment-contracts",
        family="commitments",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/commitment_contracts",
        parent_path_template=None,
        required_path_params=("company_id", "project_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object.data[]",
    ),
    EndpointAdapter(
        endpoint_id="commitment-line-items",
        family="commitments",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/commitment_contracts/{commitment_contract_id}/line_items",
        parent_path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/commitment_contracts",
        required_path_params=("company_id", "project_id", "commitment_contract_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="commitment_contract_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object.data[]",
    ),
    EndpointAdapter(
        endpoint_id="commitment-attachments",
        family="commitments",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/commitment_contracts/{commitment_contract_id}/attachments",
        parent_path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/commitment_contracts",
        required_path_params=("company_id", "project_id", "commitment_contract_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="commitment_contract_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object.data[]",
    ),
    EndpointAdapter(
        endpoint_id="commitment-compliance",
        family="commitments",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/work_order_contracts/{contract_id}/compliance",
        parent_path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/commitment_contracts",
        required_path_params=("project_id", "contract_id"),
        pagination="none",
        record_id_field="id",
        parent_record_id_field="contract_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object",
    ),
    EndpointAdapter(
        endpoint_id="commitment-change-orders",
        family="commitments",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/commitment_change_orders",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object",
    ),
    EndpointAdapter(
        endpoint_id="commitment-change-order-line-items",
        family="commitments",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/commitment_change_orders/{commitment_change_order_id}/line_items",
        parent_path_template="/rest/v1.0/projects/{project_id}/commitment_change_orders",
        required_path_params=("company_id", "project_id", "commitment_change_order_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="commitment_change_order_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object.data[]",
    ),
    # ---- Purchase orders (v1 — compatibility/backfill vs v2 commitments; see Prompt 00 §3.1) ----
    EndpointAdapter(
        endpoint_id="purchase-order-contracts",
        family="purchase_orders",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/purchase_order_contracts",
        parent_path_template=None,
        required_path_params=(),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="purchase-order-line-items",
        family="purchase_orders",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/purchase_order_contracts/{purchase_order_contract_id}/line_items",
        parent_path_template="/rest/v1.0/purchase_order_contracts",
        required_path_params=("purchase_order_contract_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="purchase_order_contract_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="purchase-order-detail-line-items",
        family="purchase_orders",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/purchase_order_contracts/{purchase_order_contract_id}/line_item_contract_details",
        parent_path_template="/rest/v1.0/purchase_order_contracts",
        required_path_params=("purchase_order_contract_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="purchase_order_contract_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    # ---- Invoices (billing periods + subcontractor invoices/requisitions) ----
    EndpointAdapter(
        endpoint_id="billing-periods",
        family="billing",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/billing_periods",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="subcontractor-invoices",
        family="subcontractor_invoices",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.1/requisitions",
        parent_path_template=None,
        required_path_params=(),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="subcontractor-invoice-contract-items",
        family="subcontractor_invoices",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/requisitions/{requisition_id}/contract_items",
        parent_path_template="/rest/v1.1/requisitions",
        required_path_params=("requisition_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="requisition_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="subcontractor-invoice-contract-detail-items",
        family="subcontractor_invoices",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/requisitions/{requisition_id}/contract_detail_items",
        parent_path_template="/rest/v1.1/requisitions",
        required_path_params=("requisition_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="requisition_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="subcontractor-invoice-change-order-items",
        family="subcontractor_invoices",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/requisitions/{requisition_id}/change_order_items",
        parent_path_template="/rest/v1.1/requisitions",
        required_path_params=("requisition_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="requisition_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    # ---- Change management (RFQs + change events) ----
    EndpointAdapter(
        endpoint_id="rfqs",
        family="change_management",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/rfqs",
        parent_path_template=None,
        required_path_params=(),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="rfq-responses",
        family="change_management",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/rfqs/{rfq_id}/responses",
        parent_path_template="/rest/v1.0/rfqs",
        required_path_params=("rfq_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="rfq_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="rfq-quotes",
        family="change_management",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/rfqs/{rfq_id}/quotes",
        parent_path_template="/rest/v1.0/rfqs",
        required_path_params=("rfq_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="rfq_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="change-events",
        family="change_management",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.1/change_events",
        parent_path_template=None,
        required_path_params=(),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object",
    ),
    EndpointAdapter(
        endpoint_id="change-event-comments",
        family="change_management",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/change_events/{change_event_id}/comments",
        parent_path_template="/rest/v1.1/change_events",
        required_path_params=("company_id", "project_id", "change_event_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="change_event_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object.data[]",
    ),
    # ---- Budget (views / details / rows / changes / modifications) ----
    EndpointAdapter(
        endpoint_id="budget-views",
        family="budget",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/budget_views",
        parent_path_template=None,
        required_path_params=(),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="budget-detail-columns",
        family="budget",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/budget_views/{budget_view_id}/budget_detail_columns",
        parent_path_template="/rest/v1.0/budget_views",
        required_path_params=("budget_view_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="budget_view_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="budget-details",
        family="budget",
        legacy_endpoint_alias=None,
        # Source reference carries no resolved path for this endpoint
        # (Prompt 00 §3.2). A clearly non-routable sentinel keeps the id
        # catalog-visible while guaranteeing it can never transport — the
        # path is NOT guessed. To be resolved (likely merged into
        # budget-detail-rows) before any live promotion.
        path_template="unresolved:budget-details",
        parent_path_template="/rest/v1.0/budget_views",
        required_path_params=(),
        pagination="none",
        record_id_field="id",
        parent_record_id_field="budget_view_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_unresolved_path_fail_closed_prompt00-3.2",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="budget-detail-rows",
        family="budget",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/budget_views/{budget_view_id}/detail_rows",
        parent_path_template="/rest/v1.0/budget_views",
        required_path_params=("budget_view_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field="budget_view_id",
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="array",
    ),
    EndpointAdapter(
        endpoint_id="budget-change-history",
        family="budget",
        legacy_endpoint_alias=None,
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/budget_change_history",
        parent_path_template=None,
        required_path_params=("company_id", "project_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="object",
    ),
    EndpointAdapter(
        endpoint_id="budget-change-line-items",
        family="budget",
        legacy_endpoint_alias=None,
        # Path carries no parent change-history id token — it is a
        # project-scoped adjustment-line-item list, so parent_record_id_field
        # is None even though it is grouped under budget-change-history.
        path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/budget_changes/adjustment_line_items",
        parent_path_template="/rest/v2.0/companies/{company_id}/projects/{project_id}/budget_change_history",
        required_path_params=("company_id", "project_id"),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=False,
        verification_reason="phase05_shell_pending_live_smoke",
        response_envelope="object.data[]",
    ),
    EndpointAdapter(
        endpoint_id="budget-modifications",
        family="budget",
        legacy_endpoint_alias=None,
        path_template="/rest/v1.0/projects/{project_id}/budget_modifications",
        parent_path_template=None,
        required_path_params=("project_id",),
        pagination="page+per_page",
        record_id_field="id",
        parent_record_id_field=None,
        review_required_default=True,
        sensitivity="high",
        sqlite_target="procore_live_records",
        live_verified=True,
        verification_reason="phase05_live_smoke_verified_2026-05-29",
        response_envelope="array",
    ),
)

_BY_ID: Dict[str, EndpointAdapter] = {ep.endpoint_id: ep for ep in _ENDPOINTS}
_BY_LEGACY: Dict[str, EndpointAdapter] = {
    ep.legacy_endpoint_alias: ep for ep in _ENDPOINTS if ep.legacy_endpoint_alias is not None
}


def get(endpoint_id: str) -> Optional[EndpointAdapter]:
    """Resolve by canonical id; fall back to legacy alias for backward compatibility."""
    if endpoint_id in _BY_ID:
        return _BY_ID[endpoint_id]
    return _BY_LEGACY.get(endpoint_id)


def list_all() -> List[EndpointAdapter]:
    """Return the full canonical registry in declaration order."""
    return list(_ENDPOINTS)


def list_verified() -> List[EndpointAdapter]:
    """Return only the live-verified adapters."""
    return [ep for ep in _ENDPOINTS if ep.live_verified]


def is_known(endpoint_id: str) -> bool:
    return endpoint_id in _BY_ID or endpoint_id in _BY_LEGACY


__all__ = [
    "EndpointAdapter",
    "get",
    "is_known",
    "list_all",
    "list_verified",
]
